// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type InitOrgCaRequest struct {
	OrgName     string  `json:"org_name" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
}

type IssueMemberCertRequest struct {
	MemberEmail string            `json:"member_email" url:"-"`
	Role        string            `json:"role" url:"-"`
	Description *string           `json:"description,omitempty" url:"-"`
	Metadata    map[string]string `json:"metadata,omitempty" url:"-"`
}

type RevokeCertRequest struct {
	Reason int `json:"reason" url:"-"`
}

type CertificateListResponse = []*CertificateListResponseItem

type CertificateListResponseItem struct {
	Id           string             `json:"id" url:"id"`
	OrgId        string             `json:"org_id" url:"org_id"`
	SerialHex    string             `json:"serial_hex" url:"serial_hex"`
	CertType     string             `json:"cert_type" url:"cert_type"`
	SubjectCn    string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status       string             `json:"status" url:"status"`
	NotBefore    *string            `json:"not_before,omitempty" url:"not_before,omitempty"`
	NotAfter     *string            `json:"not_after,omitempty" url:"not_after,omitempty"`
	Description  *string            `json:"description,omitempty" url:"description,omitempty"`
	Metadata     map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	RevokedAt    *string            `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	CreatedAt    string             `json:"created_at" url:"created_at"`
	UpdatedAt    string             `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CertificateListResponseItem) GetId() string {
	if c == nil {
		return ""
	}
	return c.Id
}

func (c *CertificateListResponseItem) GetOrgId() string {
	if c == nil {
		return ""
	}
	return c.OrgId
}

func (c *CertificateListResponseItem) GetSerialHex() string {
	if c == nil {
		return ""
	}
	return c.SerialHex
}

func (c *CertificateListResponseItem) GetCertType() string {
	if c == nil {
		return ""
	}
	return c.CertType
}

func (c *CertificateListResponseItem) GetSubjectCn() string {
	if c == nil {
		return ""
	}
	return c.SubjectCn
}

func (c *CertificateListResponseItem) GetSubjectEmail() *string {
	if c == nil {
		return nil
	}
	return c.SubjectEmail
}

func (c *CertificateListResponseItem) GetStatus() string {
	if c == nil {
		return ""
	}
	return c.Status
}

func (c *CertificateListResponseItem) GetNotBefore() *string {
	if c == nil {
		return nil
	}
	return c.NotBefore
}

func (c *CertificateListResponseItem) GetNotAfter() *string {
	if c == nil {
		return nil
	}
	return c.NotAfter
}

func (c *CertificateListResponseItem) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CertificateListResponseItem) GetMetadata() map[string]*string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CertificateListResponseItem) GetRevokedAt() *string {
	if c == nil {
		return nil
	}
	return c.RevokedAt
}

func (c *CertificateListResponseItem) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CertificateListResponseItem) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CertificateListResponseItem) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CertificateListResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler CertificateListResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CertificateListResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CertificateListResponseItem) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CrlResponse struct {
	CrlPem    string  `json:"crl_pem" url:"crl_pem"`
	CrlNumber float64 `json:"crl_number" url:"crl_number"`
	IsDelta   bool    `json:"is_delta" url:"is_delta"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CrlResponse) GetCrlPem() string {
	if c == nil {
		return ""
	}
	return c.CrlPem
}

func (c *CrlResponse) GetCrlNumber() float64 {
	if c == nil {
		return 0
	}
	return c.CrlNumber
}

func (c *CrlResponse) GetIsDelta() bool {
	if c == nil {
		return false
	}
	return c.IsDelta
}

func (c *CrlResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CrlResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CrlResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CrlResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CrlResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type MemberCertResponse struct {
	Id           string             `json:"id" url:"id"`
	OrgId        string             `json:"org_id" url:"org_id"`
	SerialHex    string             `json:"serial_hex" url:"serial_hex"`
	CertType     string             `json:"cert_type" url:"cert_type"`
	SubjectCn    string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status       string             `json:"status" url:"status"`
	Metadata     map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	CertPem      string             `json:"cert_pem" url:"cert_pem"`
	KeyPem       string             `json:"key_pem" url:"key_pem"`
	CreatedAt    string             `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MemberCertResponse) GetId() string {
	if m == nil {
		return ""
	}
	return m.Id
}

func (m *MemberCertResponse) GetOrgId() string {
	if m == nil {
		return ""
	}
	return m.OrgId
}

func (m *MemberCertResponse) GetSerialHex() string {
	if m == nil {
		return ""
	}
	return m.SerialHex
}

func (m *MemberCertResponse) GetCertType() string {
	if m == nil {
		return ""
	}
	return m.CertType
}

func (m *MemberCertResponse) GetSubjectCn() string {
	if m == nil {
		return ""
	}
	return m.SubjectCn
}

func (m *MemberCertResponse) GetSubjectEmail() *string {
	if m == nil {
		return nil
	}
	return m.SubjectEmail
}

func (m *MemberCertResponse) GetStatus() string {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MemberCertResponse) GetMetadata() map[string]*string {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *MemberCertResponse) GetCertPem() string {
	if m == nil {
		return ""
	}
	return m.CertPem
}

func (m *MemberCertResponse) GetKeyPem() string {
	if m == nil {
		return ""
	}
	return m.KeyPem
}

func (m *MemberCertResponse) GetCreatedAt() string {
	if m == nil {
		return ""
	}
	return m.CreatedAt
}

func (m *MemberCertResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MemberCertResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MemberCertResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MemberCertResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MemberCertResponse) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type OcspResponse struct {
	Status    string  `json:"status" url:"status"`
	RevokedAt *string `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OcspResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OcspResponse) GetRevokedAt() *string {
	if o == nil {
		return nil
	}
	return o.RevokedAt
}

func (o *OcspResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OcspResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OcspResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OcspResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OcspResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgCaResponse struct {
	Id        string  `json:"id" url:"id"`
	OrgId     string  `json:"org_id" url:"org_id"`
	SerialHex string  `json:"serial_hex" url:"serial_hex"`
	CertType  string  `json:"cert_type" url:"cert_type"`
	SubjectCn string  `json:"subject_cn" url:"subject_cn"`
	Status    string  `json:"status" url:"status"`
	CertPem   *string `json:"cert_pem,omitempty" url:"cert_pem,omitempty"`
	CreatedAt string  `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgCaResponse) GetId() string {
	if o == nil {
		return ""
	}
	return o.Id
}

func (o *OrgCaResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgCaResponse) GetSerialHex() string {
	if o == nil {
		return ""
	}
	return o.SerialHex
}

func (o *OrgCaResponse) GetCertType() string {
	if o == nil {
		return ""
	}
	return o.CertType
}

func (o *OrgCaResponse) GetSubjectCn() string {
	if o == nil {
		return ""
	}
	return o.SubjectCn
}

func (o *OrgCaResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgCaResponse) GetCertPem() *string {
	if o == nil {
		return nil
	}
	return o.CertPem
}

func (o *OrgCaResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *OrgCaResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgCaResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgCaResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgCaResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgCaResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type RevokeCertResponse struct {
	Message   string `json:"message" url:"message"`
	SerialHex string `json:"serial_hex" url:"serial_hex"`
	Status    string `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeCertResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RevokeCertResponse) GetSerialHex() string {
	if r == nil {
		return ""
	}
	return r.SerialHex
}

func (r *RevokeCertResponse) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *RevokeCertResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeCertResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeCertResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeCertResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeCertResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RootCaResponse struct {
	CertPem string `json:"cert_pem" url:"cert_pem"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RootCaResponse) GetCertPem() string {
	if r == nil {
		return ""
	}
	return r.CertPem
}

func (r *RootCaResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RootCaResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RootCaResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RootCaResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RootCaResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
