// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type ImportChainRequest struct {
	ChainPem    string  `json:"chain_pem" url:"-"`
	EnvTypeId   *string `json:"env_type_id,omitempty" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
}

type InitOrgCaRequest struct {
	OrgName     string  `json:"org_name" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
}

type IssueLeafCertRequest struct {
	AppId        string                            `json:"app_id" url:"-"`
	EnvTypeId    *string                           `json:"env_type_id,omitempty" url:"-"`
	CommonName   string                            `json:"common_name" url:"-"`
	Sans         []string                          `json:"sans,omitempty" url:"-"`
	TtlDays      *int                              `json:"ttl_days,omitempty" url:"-"`
	KeyAlgorithm *IssueLeafCertRequestKeyAlgorithm `json:"key_algorithm,omitempty" url:"-"`
	Description  *string                           `json:"description,omitempty" url:"-"`
}

type IssueMemberCertRequest struct {
	MemberEmail string            `json:"member_email" url:"-"`
	Role        *string           `json:"role,omitempty" url:"-"`
	Description *string           `json:"description,omitempty" url:"-"`
	Metadata    map[string]string `json:"metadata,omitempty" url:"-"`
}

type LabelEnvCaRequest struct {
	EnvTypeId string  `json:"env_type_id" url:"-"`
	Name      *string `json:"name,omitempty" url:"-"`
}

type RenewCertRequest struct {
	Description    *string `json:"description,omitempty" url:"-"`
	RevokePrevious *bool   `json:"revoke_previous,omitempty" url:"-"`
}

type RevokeCertRequest struct {
	Reason int `json:"reason" url:"-"`
}

type RotateCertRequest struct {
	Description    *string `json:"description,omitempty" url:"-"`
	RevokePrevious *bool   `json:"revoke_previous,omitempty" url:"-"`
	Reason         *int    `json:"reason,omitempty" url:"-"`
}

type SetAutoRenewRequest struct {
	AutoRenew       bool    `json:"auto_renew" url:"-"`
	RenewDaysBefore *int    `json:"renew_days_before,omitempty" url:"-"`
	EnvTypeId       *string `json:"env_type_id,omitempty" url:"-"`
}

type SignCsrRequest struct {
	AppId       *string `json:"app_id,omitempty" url:"-"`
	CsrPem      string  `json:"csr_pem" url:"-"`
	TtlDays     *int    `json:"ttl_days,omitempty" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
}

type BaseCertificateResponse struct {
	Id                      string             `json:"id" url:"id"`
	OrgId                   string             `json:"org_id" url:"org_id"`
	SerialHex               string             `json:"serial_hex" url:"serial_hex"`
	CertType                string             `json:"cert_type" url:"cert_type"`
	SubjectCn               string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail            *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status                  string             `json:"status" url:"status"`
	Description             *string            `json:"description,omitempty" url:"description,omitempty"`
	Metadata                map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	CertPem                 *string            `json:"cert_pem,omitempty" url:"cert_pem,omitempty"`
	IsSystemGenerated       bool               `json:"is_system_generated" url:"is_system_generated"`
	NotBefore               *string            `json:"not_before,omitempty" url:"not_before,omitempty"`
	NotAfter                *string            `json:"not_after,omitempty" url:"not_after,omitempty"`
	RevokedAt               *string            `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	SupersedesCertificateId *string            `json:"supersedes_certificate_id,omitempty" url:"supersedes_certificate_id,omitempty"`
	CreatedAt               string             `json:"created_at" url:"created_at"`
	UpdatedAt               string             `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (b *BaseCertificateResponse) GetId() string {
	if b == nil {
		return ""
	}
	return b.Id
}

func (b *BaseCertificateResponse) GetOrgId() string {
	if b == nil {
		return ""
	}
	return b.OrgId
}

func (b *BaseCertificateResponse) GetSerialHex() string {
	if b == nil {
		return ""
	}
	return b.SerialHex
}

func (b *BaseCertificateResponse) GetCertType() string {
	if b == nil {
		return ""
	}
	return b.CertType
}

func (b *BaseCertificateResponse) GetSubjectCn() string {
	if b == nil {
		return ""
	}
	return b.SubjectCn
}

func (b *BaseCertificateResponse) GetSubjectEmail() *string {
	if b == nil {
		return nil
	}
	return b.SubjectEmail
}

func (b *BaseCertificateResponse) GetStatus() string {
	if b == nil {
		return ""
	}
	return b.Status
}

func (b *BaseCertificateResponse) GetDescription() *string {
	if b == nil {
		return nil
	}
	return b.Description
}

func (b *BaseCertificateResponse) GetMetadata() map[string]*string {
	if b == nil {
		return nil
	}
	return b.Metadata
}

func (b *BaseCertificateResponse) GetCertPem() *string {
	if b == nil {
		return nil
	}
	return b.CertPem
}

func (b *BaseCertificateResponse) GetIsSystemGenerated() bool {
	if b == nil {
		return false
	}
	return b.IsSystemGenerated
}

func (b *BaseCertificateResponse) GetNotBefore() *string {
	if b == nil {
		return nil
	}
	return b.NotBefore
}

func (b *BaseCertificateResponse) GetNotAfter() *string {
	if b == nil {
		return nil
	}
	return b.NotAfter
}

func (b *BaseCertificateResponse) GetRevokedAt() *string {
	if b == nil {
		return nil
	}
	return b.RevokedAt
}

func (b *BaseCertificateResponse) GetSupersedesCertificateId() *string {
	if b == nil {
		return nil
	}
	return b.SupersedesCertificateId
}

func (b *BaseCertificateResponse) GetCreatedAt() string {
	if b == nil {
		return ""
	}
	return b.CreatedAt
}

func (b *BaseCertificateResponse) GetUpdatedAt() string {
	if b == nil {
		return ""
	}
	return b.UpdatedAt
}

func (b *BaseCertificateResponse) GetExtraProperties() map[string]interface{} {
	return b.extraProperties
}

func (b *BaseCertificateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler BaseCertificateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*b = BaseCertificateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *b)
	if err != nil {
		return err
	}
	b.extraProperties = extraProperties
	b.rawJSON = json.RawMessage(data)
	return nil
}

func (b *BaseCertificateResponse) String() string {
	if len(b.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(b.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type CertificateChainResponse struct {
	ChainPem      string  `json:"chain_pem" url:"chain_pem"`
	OrgCaPem      *string `json:"org_ca_pem,omitempty" url:"org_ca_pem,omitempty"`
	RootCaPem     string  `json:"root_ca_pem" url:"root_ca_pem"`
	ImportedCount int     `json:"imported_count" url:"imported_count"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CertificateChainResponse) GetChainPem() string {
	if c == nil {
		return ""
	}
	return c.ChainPem
}

func (c *CertificateChainResponse) GetOrgCaPem() *string {
	if c == nil {
		return nil
	}
	return c.OrgCaPem
}

func (c *CertificateChainResponse) GetRootCaPem() string {
	if c == nil {
		return ""
	}
	return c.RootCaPem
}

func (c *CertificateChainResponse) GetImportedCount() int {
	if c == nil {
		return 0
	}
	return c.ImportedCount
}

func (c *CertificateChainResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CertificateChainResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CertificateChainResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CertificateChainResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CertificateChainResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CertificateListResponse = []*BaseCertificateResponse

type CrlResponse struct {
	CrlPem    string  `json:"crl_pem" url:"crl_pem"`
	CrlNumber float64 `json:"crl_number" url:"crl_number"`
	IsDelta   bool    `json:"is_delta" url:"is_delta"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CrlResponse) GetCrlPem() string {
	if c == nil {
		return ""
	}
	return c.CrlPem
}

func (c *CrlResponse) GetCrlNumber() float64 {
	if c == nil {
		return 0
	}
	return c.CrlNumber
}

func (c *CrlResponse) GetIsDelta() bool {
	if c == nil {
		return false
	}
	return c.IsDelta
}

func (c *CrlResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CrlResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CrlResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CrlResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CrlResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type MemberCertResponse struct {
	Id                      string             `json:"id" url:"id"`
	OrgId                   string             `json:"org_id" url:"org_id"`
	SerialHex               string             `json:"serial_hex" url:"serial_hex"`
	CertType                string             `json:"cert_type" url:"cert_type"`
	SubjectCn               string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail            *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status                  string             `json:"status" url:"status"`
	Description             *string            `json:"description,omitempty" url:"description,omitempty"`
	Metadata                map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	CertPem                 *string            `json:"cert_pem,omitempty" url:"cert_pem,omitempty"`
	IsSystemGenerated       bool               `json:"is_system_generated" url:"is_system_generated"`
	NotBefore               *string            `json:"not_before,omitempty" url:"not_before,omitempty"`
	NotAfter                *string            `json:"not_after,omitempty" url:"not_after,omitempty"`
	RevokedAt               *string            `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	SupersedesCertificateId *string            `json:"supersedes_certificate_id,omitempty" url:"supersedes_certificate_id,omitempty"`
	CreatedAt               string             `json:"created_at" url:"created_at"`
	UpdatedAt               string             `json:"updated_at" url:"updated_at"`
	KeyPem                  string             `json:"key_pem" url:"key_pem"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MemberCertResponse) GetId() string {
	if m == nil {
		return ""
	}
	return m.Id
}

func (m *MemberCertResponse) GetOrgId() string {
	if m == nil {
		return ""
	}
	return m.OrgId
}

func (m *MemberCertResponse) GetSerialHex() string {
	if m == nil {
		return ""
	}
	return m.SerialHex
}

func (m *MemberCertResponse) GetCertType() string {
	if m == nil {
		return ""
	}
	return m.CertType
}

func (m *MemberCertResponse) GetSubjectCn() string {
	if m == nil {
		return ""
	}
	return m.SubjectCn
}

func (m *MemberCertResponse) GetSubjectEmail() *string {
	if m == nil {
		return nil
	}
	return m.SubjectEmail
}

func (m *MemberCertResponse) GetStatus() string {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MemberCertResponse) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *MemberCertResponse) GetMetadata() map[string]*string {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *MemberCertResponse) GetCertPem() *string {
	if m == nil {
		return nil
	}
	return m.CertPem
}

func (m *MemberCertResponse) GetIsSystemGenerated() bool {
	if m == nil {
		return false
	}
	return m.IsSystemGenerated
}

func (m *MemberCertResponse) GetNotBefore() *string {
	if m == nil {
		return nil
	}
	return m.NotBefore
}

func (m *MemberCertResponse) GetNotAfter() *string {
	if m == nil {
		return nil
	}
	return m.NotAfter
}

func (m *MemberCertResponse) GetRevokedAt() *string {
	if m == nil {
		return nil
	}
	return m.RevokedAt
}

func (m *MemberCertResponse) GetSupersedesCertificateId() *string {
	if m == nil {
		return nil
	}
	return m.SupersedesCertificateId
}

func (m *MemberCertResponse) GetCreatedAt() string {
	if m == nil {
		return ""
	}
	return m.CreatedAt
}

func (m *MemberCertResponse) GetUpdatedAt() string {
	if m == nil {
		return ""
	}
	return m.UpdatedAt
}

func (m *MemberCertResponse) GetKeyPem() string {
	if m == nil {
		return ""
	}
	return m.KeyPem
}

func (m *MemberCertResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MemberCertResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MemberCertResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MemberCertResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MemberCertResponse) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MyCertificateBundleResponse struct {
	RootCaPem         string                                        `json:"root_ca_pem" url:"root_ca_pem"`
	MemberCertificate *MyCertificateBundleResponseMemberCertificate `json:"member_certificate" url:"member_certificate"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MyCertificateBundleResponse) GetRootCaPem() string {
	if m == nil {
		return ""
	}
	return m.RootCaPem
}

func (m *MyCertificateBundleResponse) GetMemberCertificate() *MyCertificateBundleResponseMemberCertificate {
	if m == nil {
		return nil
	}
	return m.MemberCertificate
}

func (m *MyCertificateBundleResponse) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MyCertificateBundleResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MyCertificateBundleResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MyCertificateBundleResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MyCertificateBundleResponse) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MyCertificateBundleResponseMemberCertificate struct {
	Id                      string             `json:"id" url:"id"`
	OrgId                   string             `json:"org_id" url:"org_id"`
	SerialHex               string             `json:"serial_hex" url:"serial_hex"`
	CertType                string             `json:"cert_type" url:"cert_type"`
	SubjectCn               string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail            *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status                  string             `json:"status" url:"status"`
	Description             *string            `json:"description,omitempty" url:"description,omitempty"`
	Metadata                map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	CertPem                 *string            `json:"cert_pem,omitempty" url:"cert_pem,omitempty"`
	IsSystemGenerated       bool               `json:"is_system_generated" url:"is_system_generated"`
	NotBefore               *string            `json:"not_before,omitempty" url:"not_before,omitempty"`
	NotAfter                *string            `json:"not_after,omitempty" url:"not_after,omitempty"`
	RevokedAt               *string            `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	SupersedesCertificateId *string            `json:"supersedes_certificate_id,omitempty" url:"supersedes_certificate_id,omitempty"`
	CreatedAt               string             `json:"created_at" url:"created_at"`
	UpdatedAt               string             `json:"updated_at" url:"updated_at"`
	KeyPem                  string             `json:"key_pem" url:"key_pem"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MyCertificateBundleResponseMemberCertificate) GetId() string {
	if m == nil {
		return ""
	}
	return m.Id
}

func (m *MyCertificateBundleResponseMemberCertificate) GetOrgId() string {
	if m == nil {
		return ""
	}
	return m.OrgId
}

func (m *MyCertificateBundleResponseMemberCertificate) GetSerialHex() string {
	if m == nil {
		return ""
	}
	return m.SerialHex
}

func (m *MyCertificateBundleResponseMemberCertificate) GetCertType() string {
	if m == nil {
		return ""
	}
	return m.CertType
}

func (m *MyCertificateBundleResponseMemberCertificate) GetSubjectCn() string {
	if m == nil {
		return ""
	}
	return m.SubjectCn
}

func (m *MyCertificateBundleResponseMemberCertificate) GetSubjectEmail() *string {
	if m == nil {
		return nil
	}
	return m.SubjectEmail
}

func (m *MyCertificateBundleResponseMemberCertificate) GetStatus() string {
	if m == nil {
		return ""
	}
	return m.Status
}

func (m *MyCertificateBundleResponseMemberCertificate) GetDescription() *string {
	if m == nil {
		return nil
	}
	return m.Description
}

func (m *MyCertificateBundleResponseMemberCertificate) GetMetadata() map[string]*string {
	if m == nil {
		return nil
	}
	return m.Metadata
}

func (m *MyCertificateBundleResponseMemberCertificate) GetCertPem() *string {
	if m == nil {
		return nil
	}
	return m.CertPem
}

func (m *MyCertificateBundleResponseMemberCertificate) GetIsSystemGenerated() bool {
	if m == nil {
		return false
	}
	return m.IsSystemGenerated
}

func (m *MyCertificateBundleResponseMemberCertificate) GetNotBefore() *string {
	if m == nil {
		return nil
	}
	return m.NotBefore
}

func (m *MyCertificateBundleResponseMemberCertificate) GetNotAfter() *string {
	if m == nil {
		return nil
	}
	return m.NotAfter
}

func (m *MyCertificateBundleResponseMemberCertificate) GetRevokedAt() *string {
	if m == nil {
		return nil
	}
	return m.RevokedAt
}

func (m *MyCertificateBundleResponseMemberCertificate) GetSupersedesCertificateId() *string {
	if m == nil {
		return nil
	}
	return m.SupersedesCertificateId
}

func (m *MyCertificateBundleResponseMemberCertificate) GetCreatedAt() string {
	if m == nil {
		return ""
	}
	return m.CreatedAt
}

func (m *MyCertificateBundleResponseMemberCertificate) GetUpdatedAt() string {
	if m == nil {
		return ""
	}
	return m.UpdatedAt
}

func (m *MyCertificateBundleResponseMemberCertificate) GetKeyPem() string {
	if m == nil {
		return ""
	}
	return m.KeyPem
}

func (m *MyCertificateBundleResponseMemberCertificate) GetExtraProperties() map[string]interface{} {
	return m.extraProperties
}

func (m *MyCertificateBundleResponseMemberCertificate) UnmarshalJSON(data []byte) error {
	type unmarshaler MyCertificateBundleResponseMemberCertificate
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MyCertificateBundleResponseMemberCertificate(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MyCertificateBundleResponseMemberCertificate) String() string {
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type OcspResponse struct {
	Status    string  `json:"status" url:"status"`
	RevokedAt *string `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OcspResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OcspResponse) GetRevokedAt() *string {
	if o == nil {
		return nil
	}
	return o.RevokedAt
}

func (o *OcspResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OcspResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OcspResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OcspResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OcspResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgCaResponse struct {
	Id                      string             `json:"id" url:"id"`
	OrgId                   string             `json:"org_id" url:"org_id"`
	SerialHex               string             `json:"serial_hex" url:"serial_hex"`
	CertType                string             `json:"cert_type" url:"cert_type"`
	SubjectCn               string             `json:"subject_cn" url:"subject_cn"`
	SubjectEmail            *string            `json:"subject_email,omitempty" url:"subject_email,omitempty"`
	Status                  string             `json:"status" url:"status"`
	Description             *string            `json:"description,omitempty" url:"description,omitempty"`
	Metadata                map[string]*string `json:"metadata,omitempty" url:"metadata,omitempty"`
	CertPem                 *string            `json:"cert_pem,omitempty" url:"cert_pem,omitempty"`
	IsSystemGenerated       bool               `json:"is_system_generated" url:"is_system_generated"`
	NotBefore               *string            `json:"not_before,omitempty" url:"not_before,omitempty"`
	NotAfter                *string            `json:"not_after,omitempty" url:"not_after,omitempty"`
	RevokedAt               *string            `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	SupersedesCertificateId *string            `json:"supersedes_certificate_id,omitempty" url:"supersedes_certificate_id,omitempty"`
	CreatedAt               string             `json:"created_at" url:"created_at"`
	UpdatedAt               string             `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgCaResponse) GetId() string {
	if o == nil {
		return ""
	}
	return o.Id
}

func (o *OrgCaResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgCaResponse) GetSerialHex() string {
	if o == nil {
		return ""
	}
	return o.SerialHex
}

func (o *OrgCaResponse) GetCertType() string {
	if o == nil {
		return ""
	}
	return o.CertType
}

func (o *OrgCaResponse) GetSubjectCn() string {
	if o == nil {
		return ""
	}
	return o.SubjectCn
}

func (o *OrgCaResponse) GetSubjectEmail() *string {
	if o == nil {
		return nil
	}
	return o.SubjectEmail
}

func (o *OrgCaResponse) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgCaResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrgCaResponse) GetMetadata() map[string]*string {
	if o == nil {
		return nil
	}
	return o.Metadata
}

func (o *OrgCaResponse) GetCertPem() *string {
	if o == nil {
		return nil
	}
	return o.CertPem
}

func (o *OrgCaResponse) GetIsSystemGenerated() bool {
	if o == nil {
		return false
	}
	return o.IsSystemGenerated
}

func (o *OrgCaResponse) GetNotBefore() *string {
	if o == nil {
		return nil
	}
	return o.NotBefore
}

func (o *OrgCaResponse) GetNotAfter() *string {
	if o == nil {
		return nil
	}
	return o.NotAfter
}

func (o *OrgCaResponse) GetRevokedAt() *string {
	if o == nil {
		return nil
	}
	return o.RevokedAt
}

func (o *OrgCaResponse) GetSupersedesCertificateId() *string {
	if o == nil {
		return nil
	}
	return o.SupersedesCertificateId
}

func (o *OrgCaResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *OrgCaResponse) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *OrgCaResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgCaResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgCaResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgCaResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgCaResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type RevokeCertResponse struct {
	Message   string `json:"message" url:"message"`
	SerialHex string `json:"serial_hex" url:"serial_hex"`
	Status    string `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeCertResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RevokeCertResponse) GetSerialHex() string {
	if r == nil {
		return ""
	}
	return r.SerialHex
}

func (r *RevokeCertResponse) GetStatus() string {
	if r == nil {
		return ""
	}
	return r.Status
}

func (r *RevokeCertResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeCertResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeCertResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeCertResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeCertResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RootCaResponse struct {
	CertPem string `json:"cert_pem" url:"cert_pem"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RootCaResponse) GetCertPem() string {
	if r == nil {
		return ""
	}
	return r.CertPem
}

func (r *RootCaResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RootCaResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RootCaResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RootCaResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RootCaResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type IssueLeafCertRequestKeyAlgorithm string

const (
	IssueLeafCertRequestKeyAlgorithmEcdsaP256 IssueLeafCertRequestKeyAlgorithm = "ECDSA_P256"
	IssueLeafCertRequestKeyAlgorithmRsa2048   IssueLeafCertRequestKeyAlgorithm = "RSA_2048"
)

func NewIssueLeafCertRequestKeyAlgorithmFromString(s string) (IssueLeafCertRequestKeyAlgorithm, error) {
	switch s {
	case "ECDSA_P256":
		return IssueLeafCertRequestKeyAlgorithmEcdsaP256, nil
	case "RSA_2048":
		return IssueLeafCertRequestKeyAlgorithmRsa2048, nil
	}
	var t IssueLeafCertRequestKeyAlgorithm
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (i IssueLeafCertRequestKeyAlgorithm) Ptr() *IssueLeafCertRequestKeyAlgorithm {
	return &i
}
