// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type CreateDynamicSecretEngineRequest struct {
	EngineType CreateDynamicSecretEngineRequestEngineType `json:"engine_type" url:"-"`
	Name       string                                     `json:"name" url:"-"`
	Config     *CreateDynamicSecretEngineRequestConfig    `json:"config,omitempty" url:"-"`
	Enabled    *bool                                      `json:"enabled,omitempty" url:"-"`
}

type CreateDynamicSecretLeaseRequest struct {
	AppId       string `json:"app_id" url:"-"`
	EnvTypeId   string `json:"env_type_id" url:"-"`
	VariableKey string `json:"variable_key" url:"-"`
	TtlSeconds  *int   `json:"ttl_seconds,omitempty" url:"-"`
}

type CleanupResponse struct {
	Cleaned int `json:"cleaned" url:"cleaned"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CleanupResponse) GetCleaned() int {
	if c == nil {
		return 0
	}
	return c.Cleaned
}

func (c *CleanupResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CleanupResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CleanupResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CleanupResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CleanupResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type DynamicSecretEngineResponse struct {
	Id         string                                `json:"id" url:"id"`
	OrgId      string                                `json:"org_id" url:"org_id"`
	EngineType DynamicSecretEngineResponseEngineType `json:"engine_type" url:"engine_type"`
	Name       string                                `json:"name" url:"name"`
	Config     map[string]interface{}                `json:"config" url:"config"`
	Enabled    bool                                  `json:"enabled" url:"enabled"`
	CreatedAt  string                                `json:"created_at" url:"created_at"`
	UpdatedAt  string                                `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DynamicSecretEngineResponse) GetId() string {
	if d == nil {
		return ""
	}
	return d.Id
}

func (d *DynamicSecretEngineResponse) GetOrgId() string {
	if d == nil {
		return ""
	}
	return d.OrgId
}

func (d *DynamicSecretEngineResponse) GetEngineType() DynamicSecretEngineResponseEngineType {
	if d == nil {
		return ""
	}
	return d.EngineType
}

func (d *DynamicSecretEngineResponse) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

func (d *DynamicSecretEngineResponse) GetConfig() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.Config
}

func (d *DynamicSecretEngineResponse) GetEnabled() bool {
	if d == nil {
		return false
	}
	return d.Enabled
}

func (d *DynamicSecretEngineResponse) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DynamicSecretEngineResponse) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DynamicSecretEngineResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DynamicSecretEngineResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DynamicSecretEngineResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DynamicSecretEngineResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DynamicSecretEngineResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DynamicSecretEngineResponseEngineType string

const (
	DynamicSecretEngineResponseEngineTypePostgres DynamicSecretEngineResponseEngineType = "postgres"
	DynamicSecretEngineResponseEngineTypeMysql    DynamicSecretEngineResponseEngineType = "mysql"
	DynamicSecretEngineResponseEngineTypeAwsIam   DynamicSecretEngineResponseEngineType = "aws-iam"
	DynamicSecretEngineResponseEngineTypeAzureSp  DynamicSecretEngineResponseEngineType = "azure-sp"
)

func NewDynamicSecretEngineResponseEngineTypeFromString(s string) (DynamicSecretEngineResponseEngineType, error) {
	switch s {
	case "postgres":
		return DynamicSecretEngineResponseEngineTypePostgres, nil
	case "mysql":
		return DynamicSecretEngineResponseEngineTypeMysql, nil
	case "aws-iam":
		return DynamicSecretEngineResponseEngineTypeAwsIam, nil
	case "azure-sp":
		return DynamicSecretEngineResponseEngineTypeAzureSp, nil
	}
	var t DynamicSecretEngineResponseEngineType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (d DynamicSecretEngineResponseEngineType) Ptr() *DynamicSecretEngineResponseEngineType {
	return &d
}

type DynamicSecretEnginesResponse = []*DynamicSecretEngineResponse

type DynamicSecretLeaseResponse struct {
	Id             string                 `json:"id" url:"id"`
	EngineId       string                 `json:"engine_id" url:"engine_id"`
	AppId          string                 `json:"app_id" url:"app_id"`
	EnvTypeId      string                 `json:"env_type_id" url:"env_type_id"`
	VariableKey    string                 `json:"variable_key" url:"variable_key"`
	CredentialData map[string]interface{} `json:"credential_data" url:"credential_data"`
	ExpiresAt      string                 `json:"expires_at" url:"expires_at"`
	RevokedAt      *string                `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	CreatedAt      string                 `json:"created_at" url:"created_at"`
	UpdatedAt      string                 `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DynamicSecretLeaseResponse) GetId() string {
	if d == nil {
		return ""
	}
	return d.Id
}

func (d *DynamicSecretLeaseResponse) GetEngineId() string {
	if d == nil {
		return ""
	}
	return d.EngineId
}

func (d *DynamicSecretLeaseResponse) GetAppId() string {
	if d == nil {
		return ""
	}
	return d.AppId
}

func (d *DynamicSecretLeaseResponse) GetEnvTypeId() string {
	if d == nil {
		return ""
	}
	return d.EnvTypeId
}

func (d *DynamicSecretLeaseResponse) GetVariableKey() string {
	if d == nil {
		return ""
	}
	return d.VariableKey
}

func (d *DynamicSecretLeaseResponse) GetCredentialData() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.CredentialData
}

func (d *DynamicSecretLeaseResponse) GetExpiresAt() string {
	if d == nil {
		return ""
	}
	return d.ExpiresAt
}

func (d *DynamicSecretLeaseResponse) GetRevokedAt() *string {
	if d == nil {
		return nil
	}
	return d.RevokedAt
}

func (d *DynamicSecretLeaseResponse) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DynamicSecretLeaseResponse) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DynamicSecretLeaseResponse) GetExtraProperties() map[string]interface{} {
	return d.extraProperties
}

func (d *DynamicSecretLeaseResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DynamicSecretLeaseResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DynamicSecretLeaseResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DynamicSecretLeaseResponse) String() string {
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type DynamicSecretLeasesResponse = []*DynamicSecretLeaseResponse

type RevokeLeaseResponse struct {
	Message string `json:"message" url:"message"`
	Id      string `json:"id" url:"id"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeLeaseResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RevokeLeaseResponse) GetId() string {
	if r == nil {
		return ""
	}
	return r.Id
}

func (r *RevokeLeaseResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeLeaseResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeLeaseResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeLeaseResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeLeaseResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type CreateDynamicSecretEngineRequestConfig struct {
	CreateDynamicSecretEngineRequestConfigZero        *CreateDynamicSecretEngineRequestConfigZero
	CreateDynamicSecretEngineRequestConfigOne         *CreateDynamicSecretEngineRequestConfigOne
	CreateDynamicSecretEngineRequestConfigAccessKeyId *CreateDynamicSecretEngineRequestConfigAccessKeyId
	CreateDynamicSecretEngineRequestConfigClientId    *CreateDynamicSecretEngineRequestConfigClientId

	typ string
}

func (c *CreateDynamicSecretEngineRequestConfig) GetCreateDynamicSecretEngineRequestConfigZero() *CreateDynamicSecretEngineRequestConfigZero {
	if c == nil {
		return nil
	}
	return c.CreateDynamicSecretEngineRequestConfigZero
}

func (c *CreateDynamicSecretEngineRequestConfig) GetCreateDynamicSecretEngineRequestConfigOne() *CreateDynamicSecretEngineRequestConfigOne {
	if c == nil {
		return nil
	}
	return c.CreateDynamicSecretEngineRequestConfigOne
}

func (c *CreateDynamicSecretEngineRequestConfig) GetCreateDynamicSecretEngineRequestConfigAccessKeyId() *CreateDynamicSecretEngineRequestConfigAccessKeyId {
	if c == nil {
		return nil
	}
	return c.CreateDynamicSecretEngineRequestConfigAccessKeyId
}

func (c *CreateDynamicSecretEngineRequestConfig) GetCreateDynamicSecretEngineRequestConfigClientId() *CreateDynamicSecretEngineRequestConfigClientId {
	if c == nil {
		return nil
	}
	return c.CreateDynamicSecretEngineRequestConfigClientId
}

func (c *CreateDynamicSecretEngineRequestConfig) UnmarshalJSON(data []byte) error {
	valueCreateDynamicSecretEngineRequestConfigZero := new(CreateDynamicSecretEngineRequestConfigZero)
	if err := json.Unmarshal(data, &valueCreateDynamicSecretEngineRequestConfigZero); err == nil {
		c.typ = "CreateDynamicSecretEngineRequestConfigZero"
		c.CreateDynamicSecretEngineRequestConfigZero = valueCreateDynamicSecretEngineRequestConfigZero
		return nil
	}
	valueCreateDynamicSecretEngineRequestConfigOne := new(CreateDynamicSecretEngineRequestConfigOne)
	if err := json.Unmarshal(data, &valueCreateDynamicSecretEngineRequestConfigOne); err == nil {
		c.typ = "CreateDynamicSecretEngineRequestConfigOne"
		c.CreateDynamicSecretEngineRequestConfigOne = valueCreateDynamicSecretEngineRequestConfigOne
		return nil
	}
	valueCreateDynamicSecretEngineRequestConfigAccessKeyId := new(CreateDynamicSecretEngineRequestConfigAccessKeyId)
	if err := json.Unmarshal(data, &valueCreateDynamicSecretEngineRequestConfigAccessKeyId); err == nil {
		c.typ = "CreateDynamicSecretEngineRequestConfigAccessKeyId"
		c.CreateDynamicSecretEngineRequestConfigAccessKeyId = valueCreateDynamicSecretEngineRequestConfigAccessKeyId
		return nil
	}
	valueCreateDynamicSecretEngineRequestConfigClientId := new(CreateDynamicSecretEngineRequestConfigClientId)
	if err := json.Unmarshal(data, &valueCreateDynamicSecretEngineRequestConfigClientId); err == nil {
		c.typ = "CreateDynamicSecretEngineRequestConfigClientId"
		c.CreateDynamicSecretEngineRequestConfigClientId = valueCreateDynamicSecretEngineRequestConfigClientId
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, c)
}

func (c CreateDynamicSecretEngineRequestConfig) MarshalJSON() ([]byte, error) {
	if c.typ == "CreateDynamicSecretEngineRequestConfigZero" || c.CreateDynamicSecretEngineRequestConfigZero != nil {
		return json.Marshal(c.CreateDynamicSecretEngineRequestConfigZero)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigOne" || c.CreateDynamicSecretEngineRequestConfigOne != nil {
		return json.Marshal(c.CreateDynamicSecretEngineRequestConfigOne)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigAccessKeyId" || c.CreateDynamicSecretEngineRequestConfigAccessKeyId != nil {
		return json.Marshal(c.CreateDynamicSecretEngineRequestConfigAccessKeyId)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigClientId" || c.CreateDynamicSecretEngineRequestConfigClientId != nil {
		return json.Marshal(c.CreateDynamicSecretEngineRequestConfigClientId)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", c)
}

type CreateDynamicSecretEngineRequestConfigVisitor interface {
	VisitCreateDynamicSecretEngineRequestConfigZero(*CreateDynamicSecretEngineRequestConfigZero) error
	VisitCreateDynamicSecretEngineRequestConfigOne(*CreateDynamicSecretEngineRequestConfigOne) error
	VisitCreateDynamicSecretEngineRequestConfigAccessKeyId(*CreateDynamicSecretEngineRequestConfigAccessKeyId) error
	VisitCreateDynamicSecretEngineRequestConfigClientId(*CreateDynamicSecretEngineRequestConfigClientId) error
}

func (c *CreateDynamicSecretEngineRequestConfig) Accept(visitor CreateDynamicSecretEngineRequestConfigVisitor) error {
	if c.typ == "CreateDynamicSecretEngineRequestConfigZero" || c.CreateDynamicSecretEngineRequestConfigZero != nil {
		return visitor.VisitCreateDynamicSecretEngineRequestConfigZero(c.CreateDynamicSecretEngineRequestConfigZero)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigOne" || c.CreateDynamicSecretEngineRequestConfigOne != nil {
		return visitor.VisitCreateDynamicSecretEngineRequestConfigOne(c.CreateDynamicSecretEngineRequestConfigOne)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigAccessKeyId" || c.CreateDynamicSecretEngineRequestConfigAccessKeyId != nil {
		return visitor.VisitCreateDynamicSecretEngineRequestConfigAccessKeyId(c.CreateDynamicSecretEngineRequestConfigAccessKeyId)
	}
	if c.typ == "CreateDynamicSecretEngineRequestConfigClientId" || c.CreateDynamicSecretEngineRequestConfigClientId != nil {
		return visitor.VisitCreateDynamicSecretEngineRequestConfigClientId(c.CreateDynamicSecretEngineRequestConfigClientId)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", c)
}

type CreateDynamicSecretEngineRequestConfigAccessKeyId struct {
	AccessKeyId       string  `json:"access_key_id" url:"access_key_id"`
	SecretAccessKey   string  `json:"secret_access_key" url:"secret_access_key"`
	Region            *string `json:"region,omitempty" url:"region,omitempty"`
	IamPolicy         string  `json:"iam_policy" url:"iam_policy"`
	DefaultTtlSeconds *int    `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds     *int    `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetAccessKeyId() string {
	if c == nil {
		return ""
	}
	return c.AccessKeyId
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetSecretAccessKey() string {
	if c == nil {
		return ""
	}
	return c.SecretAccessKey
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetRegion() *string {
	if c == nil {
		return nil
	}
	return c.Region
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetIamPolicy() string {
	if c == nil {
		return ""
	}
	return c.IamPolicy
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetDefaultTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.DefaultTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetMaxTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.MaxTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigAccessKeyId
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigAccessKeyId(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigAccessKeyId) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestConfigClientId struct {
	TenantId          string   `json:"tenant_id" url:"tenant_id"`
	ClientId          string   `json:"client_id" url:"client_id"`
	ClientSecret      string   `json:"client_secret" url:"client_secret"`
	SubscriptionId    string   `json:"subscription_id" url:"subscription_id"`
	Roles             []string `json:"roles,omitempty" url:"roles,omitempty"`
	DefaultTtlSeconds *int     `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds     *int     `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetTenantId() string {
	if c == nil {
		return ""
	}
	return c.TenantId
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetClientId() string {
	if c == nil {
		return ""
	}
	return c.ClientId
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetClientSecret() string {
	if c == nil {
		return ""
	}
	return c.ClientSecret
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetSubscriptionId() string {
	if c == nil {
		return ""
	}
	return c.SubscriptionId
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetRoles() []string {
	if c == nil {
		return nil
	}
	return c.Roles
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetDefaultTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.DefaultTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetMaxTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.MaxTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigClientId
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigClientId(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigClientId) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestConfigOne struct {
	Host               string                                              `json:"host" url:"host"`
	Port               *int                                                `json:"port,omitempty" url:"port,omitempty"`
	Database           string                                              `json:"database" url:"database"`
	Superuser          *CreateDynamicSecretEngineRequestConfigOneSuperuser `json:"superuser" url:"superuser"`
	CreationStatements []string                                            `json:"creation_statements,omitempty" url:"creation_statements,omitempty"`
	DefaultTtlSeconds  *int                                                `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds      *int                                                `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetHost() string {
	if c == nil {
		return ""
	}
	return c.Host
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetPort() *int {
	if c == nil {
		return nil
	}
	return c.Port
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetSuperuser() *CreateDynamicSecretEngineRequestConfigOneSuperuser {
	if c == nil {
		return nil
	}
	return c.Superuser
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetCreationStatements() []string {
	if c == nil {
		return nil
	}
	return c.CreationStatements
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetDefaultTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.DefaultTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetMaxTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.MaxTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigOne) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigOne) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigOne
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigOne(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigOne) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestConfigOneSuperuser struct {
	Username string `json:"username" url:"username"`
	Password string `json:"password" url:"password"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigOneSuperuser) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CreateDynamicSecretEngineRequestConfigOneSuperuser) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

func (c *CreateDynamicSecretEngineRequestConfigOneSuperuser) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigOneSuperuser) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigOneSuperuser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigOneSuperuser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigOneSuperuser) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestConfigZero struct {
	Host               string                                               `json:"host" url:"host"`
	Port               *int                                                 `json:"port,omitempty" url:"port,omitempty"`
	Database           string                                               `json:"database" url:"database"`
	Superuser          *CreateDynamicSecretEngineRequestConfigZeroSuperuser `json:"superuser" url:"superuser"`
	CreationStatements []string                                             `json:"creation_statements,omitempty" url:"creation_statements,omitempty"`
	DefaultTtlSeconds  *int                                                 `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds      *int                                                 `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetHost() string {
	if c == nil {
		return ""
	}
	return c.Host
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetPort() *int {
	if c == nil {
		return nil
	}
	return c.Port
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetDatabase() string {
	if c == nil {
		return ""
	}
	return c.Database
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetSuperuser() *CreateDynamicSecretEngineRequestConfigZeroSuperuser {
	if c == nil {
		return nil
	}
	return c.Superuser
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetCreationStatements() []string {
	if c == nil {
		return nil
	}
	return c.CreationStatements
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetDefaultTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.DefaultTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetMaxTtlSeconds() *int {
	if c == nil {
		return nil
	}
	return c.MaxTtlSeconds
}

func (c *CreateDynamicSecretEngineRequestConfigZero) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigZero) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigZero
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigZero(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigZero) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestConfigZeroSuperuser struct {
	Username string `json:"username" url:"username"`
	Password string `json:"password" url:"password"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateDynamicSecretEngineRequestConfigZeroSuperuser) GetUsername() string {
	if c == nil {
		return ""
	}
	return c.Username
}

func (c *CreateDynamicSecretEngineRequestConfigZeroSuperuser) GetPassword() string {
	if c == nil {
		return ""
	}
	return c.Password
}

func (c *CreateDynamicSecretEngineRequestConfigZeroSuperuser) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateDynamicSecretEngineRequestConfigZeroSuperuser) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateDynamicSecretEngineRequestConfigZeroSuperuser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateDynamicSecretEngineRequestConfigZeroSuperuser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateDynamicSecretEngineRequestConfigZeroSuperuser) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CreateDynamicSecretEngineRequestEngineType string

const (
	CreateDynamicSecretEngineRequestEngineTypePostgres CreateDynamicSecretEngineRequestEngineType = "postgres"
	CreateDynamicSecretEngineRequestEngineTypeMysql    CreateDynamicSecretEngineRequestEngineType = "mysql"
	CreateDynamicSecretEngineRequestEngineTypeAwsIam   CreateDynamicSecretEngineRequestEngineType = "aws-iam"
	CreateDynamicSecretEngineRequestEngineTypeAzureSp  CreateDynamicSecretEngineRequestEngineType = "azure-sp"
)

func NewCreateDynamicSecretEngineRequestEngineTypeFromString(s string) (CreateDynamicSecretEngineRequestEngineType, error) {
	switch s {
	case "postgres":
		return CreateDynamicSecretEngineRequestEngineTypePostgres, nil
	case "mysql":
		return CreateDynamicSecretEngineRequestEngineTypeMysql, nil
	case "aws-iam":
		return CreateDynamicSecretEngineRequestEngineTypeAwsIam, nil
	case "azure-sp":
		return CreateDynamicSecretEngineRequestEngineTypeAzureSp, nil
	}
	var t CreateDynamicSecretEngineRequestEngineType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateDynamicSecretEngineRequestEngineType) Ptr() *CreateDynamicSecretEngineRequestEngineType {
	return &c
}

type UpdateDynamicSecretEngineRequestConfig struct {
	UpdateDynamicSecretEngineRequestConfigZero        *UpdateDynamicSecretEngineRequestConfigZero
	UpdateDynamicSecretEngineRequestConfigOne         *UpdateDynamicSecretEngineRequestConfigOne
	UpdateDynamicSecretEngineRequestConfigAccessKeyId *UpdateDynamicSecretEngineRequestConfigAccessKeyId
	UpdateDynamicSecretEngineRequestConfigClientId    *UpdateDynamicSecretEngineRequestConfigClientId

	typ string
}

func (u *UpdateDynamicSecretEngineRequestConfig) GetUpdateDynamicSecretEngineRequestConfigZero() *UpdateDynamicSecretEngineRequestConfigZero {
	if u == nil {
		return nil
	}
	return u.UpdateDynamicSecretEngineRequestConfigZero
}

func (u *UpdateDynamicSecretEngineRequestConfig) GetUpdateDynamicSecretEngineRequestConfigOne() *UpdateDynamicSecretEngineRequestConfigOne {
	if u == nil {
		return nil
	}
	return u.UpdateDynamicSecretEngineRequestConfigOne
}

func (u *UpdateDynamicSecretEngineRequestConfig) GetUpdateDynamicSecretEngineRequestConfigAccessKeyId() *UpdateDynamicSecretEngineRequestConfigAccessKeyId {
	if u == nil {
		return nil
	}
	return u.UpdateDynamicSecretEngineRequestConfigAccessKeyId
}

func (u *UpdateDynamicSecretEngineRequestConfig) GetUpdateDynamicSecretEngineRequestConfigClientId() *UpdateDynamicSecretEngineRequestConfigClientId {
	if u == nil {
		return nil
	}
	return u.UpdateDynamicSecretEngineRequestConfigClientId
}

func (u *UpdateDynamicSecretEngineRequestConfig) UnmarshalJSON(data []byte) error {
	valueUpdateDynamicSecretEngineRequestConfigZero := new(UpdateDynamicSecretEngineRequestConfigZero)
	if err := json.Unmarshal(data, &valueUpdateDynamicSecretEngineRequestConfigZero); err == nil {
		u.typ = "UpdateDynamicSecretEngineRequestConfigZero"
		u.UpdateDynamicSecretEngineRequestConfigZero = valueUpdateDynamicSecretEngineRequestConfigZero
		return nil
	}
	valueUpdateDynamicSecretEngineRequestConfigOne := new(UpdateDynamicSecretEngineRequestConfigOne)
	if err := json.Unmarshal(data, &valueUpdateDynamicSecretEngineRequestConfigOne); err == nil {
		u.typ = "UpdateDynamicSecretEngineRequestConfigOne"
		u.UpdateDynamicSecretEngineRequestConfigOne = valueUpdateDynamicSecretEngineRequestConfigOne
		return nil
	}
	valueUpdateDynamicSecretEngineRequestConfigAccessKeyId := new(UpdateDynamicSecretEngineRequestConfigAccessKeyId)
	if err := json.Unmarshal(data, &valueUpdateDynamicSecretEngineRequestConfigAccessKeyId); err == nil {
		u.typ = "UpdateDynamicSecretEngineRequestConfigAccessKeyId"
		u.UpdateDynamicSecretEngineRequestConfigAccessKeyId = valueUpdateDynamicSecretEngineRequestConfigAccessKeyId
		return nil
	}
	valueUpdateDynamicSecretEngineRequestConfigClientId := new(UpdateDynamicSecretEngineRequestConfigClientId)
	if err := json.Unmarshal(data, &valueUpdateDynamicSecretEngineRequestConfigClientId); err == nil {
		u.typ = "UpdateDynamicSecretEngineRequestConfigClientId"
		u.UpdateDynamicSecretEngineRequestConfigClientId = valueUpdateDynamicSecretEngineRequestConfigClientId
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, u)
}

func (u UpdateDynamicSecretEngineRequestConfig) MarshalJSON() ([]byte, error) {
	if u.typ == "UpdateDynamicSecretEngineRequestConfigZero" || u.UpdateDynamicSecretEngineRequestConfigZero != nil {
		return json.Marshal(u.UpdateDynamicSecretEngineRequestConfigZero)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigOne" || u.UpdateDynamicSecretEngineRequestConfigOne != nil {
		return json.Marshal(u.UpdateDynamicSecretEngineRequestConfigOne)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigAccessKeyId" || u.UpdateDynamicSecretEngineRequestConfigAccessKeyId != nil {
		return json.Marshal(u.UpdateDynamicSecretEngineRequestConfigAccessKeyId)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigClientId" || u.UpdateDynamicSecretEngineRequestConfigClientId != nil {
		return json.Marshal(u.UpdateDynamicSecretEngineRequestConfigClientId)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateDynamicSecretEngineRequestConfigVisitor interface {
	VisitUpdateDynamicSecretEngineRequestConfigZero(*UpdateDynamicSecretEngineRequestConfigZero) error
	VisitUpdateDynamicSecretEngineRequestConfigOne(*UpdateDynamicSecretEngineRequestConfigOne) error
	VisitUpdateDynamicSecretEngineRequestConfigAccessKeyId(*UpdateDynamicSecretEngineRequestConfigAccessKeyId) error
	VisitUpdateDynamicSecretEngineRequestConfigClientId(*UpdateDynamicSecretEngineRequestConfigClientId) error
}

func (u *UpdateDynamicSecretEngineRequestConfig) Accept(visitor UpdateDynamicSecretEngineRequestConfigVisitor) error {
	if u.typ == "UpdateDynamicSecretEngineRequestConfigZero" || u.UpdateDynamicSecretEngineRequestConfigZero != nil {
		return visitor.VisitUpdateDynamicSecretEngineRequestConfigZero(u.UpdateDynamicSecretEngineRequestConfigZero)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigOne" || u.UpdateDynamicSecretEngineRequestConfigOne != nil {
		return visitor.VisitUpdateDynamicSecretEngineRequestConfigOne(u.UpdateDynamicSecretEngineRequestConfigOne)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigAccessKeyId" || u.UpdateDynamicSecretEngineRequestConfigAccessKeyId != nil {
		return visitor.VisitUpdateDynamicSecretEngineRequestConfigAccessKeyId(u.UpdateDynamicSecretEngineRequestConfigAccessKeyId)
	}
	if u.typ == "UpdateDynamicSecretEngineRequestConfigClientId" || u.UpdateDynamicSecretEngineRequestConfigClientId != nil {
		return visitor.VisitUpdateDynamicSecretEngineRequestConfigClientId(u.UpdateDynamicSecretEngineRequestConfigClientId)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", u)
}

type UpdateDynamicSecretEngineRequestConfigAccessKeyId struct {
	AccessKeyId       string  `json:"access_key_id" url:"access_key_id"`
	SecretAccessKey   string  `json:"secret_access_key" url:"secret_access_key"`
	Region            *string `json:"region,omitempty" url:"region,omitempty"`
	IamPolicy         string  `json:"iam_policy" url:"iam_policy"`
	DefaultTtlSeconds *int    `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds     *int    `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetAccessKeyId() string {
	if u == nil {
		return ""
	}
	return u.AccessKeyId
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetSecretAccessKey() string {
	if u == nil {
		return ""
	}
	return u.SecretAccessKey
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetRegion() *string {
	if u == nil {
		return nil
	}
	return u.Region
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetIamPolicy() string {
	if u == nil {
		return ""
	}
	return u.IamPolicy
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetDefaultTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.DefaultTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetMaxTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.MaxTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigAccessKeyId
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigAccessKeyId(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigAccessKeyId) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequestConfigClientId struct {
	TenantId          string   `json:"tenant_id" url:"tenant_id"`
	ClientId          string   `json:"client_id" url:"client_id"`
	ClientSecret      string   `json:"client_secret" url:"client_secret"`
	SubscriptionId    string   `json:"subscription_id" url:"subscription_id"`
	Roles             []string `json:"roles,omitempty" url:"roles,omitempty"`
	DefaultTtlSeconds *int     `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds     *int     `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetTenantId() string {
	if u == nil {
		return ""
	}
	return u.TenantId
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetClientId() string {
	if u == nil {
		return ""
	}
	return u.ClientId
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetClientSecret() string {
	if u == nil {
		return ""
	}
	return u.ClientSecret
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetSubscriptionId() string {
	if u == nil {
		return ""
	}
	return u.SubscriptionId
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetRoles() []string {
	if u == nil {
		return nil
	}
	return u.Roles
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetDefaultTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.DefaultTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetMaxTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.MaxTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigClientId
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigClientId(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigClientId) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequestConfigOne struct {
	Host               string                                              `json:"host" url:"host"`
	Port               *int                                                `json:"port,omitempty" url:"port,omitempty"`
	Database           string                                              `json:"database" url:"database"`
	Superuser          *UpdateDynamicSecretEngineRequestConfigOneSuperuser `json:"superuser" url:"superuser"`
	CreationStatements []string                                            `json:"creation_statements,omitempty" url:"creation_statements,omitempty"`
	DefaultTtlSeconds  *int                                                `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds      *int                                                `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetHost() string {
	if u == nil {
		return ""
	}
	return u.Host
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetPort() *int {
	if u == nil {
		return nil
	}
	return u.Port
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetSuperuser() *UpdateDynamicSecretEngineRequestConfigOneSuperuser {
	if u == nil {
		return nil
	}
	return u.Superuser
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetCreationStatements() []string {
	if u == nil {
		return nil
	}
	return u.CreationStatements
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetDefaultTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.DefaultTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetMaxTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.MaxTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigOne
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigOne(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigOne) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequestConfigOneSuperuser struct {
	Username string `json:"username" url:"username"`
	Password string `json:"password" url:"password"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigOneSuperuser) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UpdateDynamicSecretEngineRequestConfigOneSuperuser) GetPassword() string {
	if u == nil {
		return ""
	}
	return u.Password
}

func (u *UpdateDynamicSecretEngineRequestConfigOneSuperuser) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigOneSuperuser) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigOneSuperuser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigOneSuperuser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigOneSuperuser) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequestConfigZero struct {
	Host               string                                               `json:"host" url:"host"`
	Port               *int                                                 `json:"port,omitempty" url:"port,omitempty"`
	Database           string                                               `json:"database" url:"database"`
	Superuser          *UpdateDynamicSecretEngineRequestConfigZeroSuperuser `json:"superuser" url:"superuser"`
	CreationStatements []string                                             `json:"creation_statements,omitempty" url:"creation_statements,omitempty"`
	DefaultTtlSeconds  *int                                                 `json:"default_ttl_seconds,omitempty" url:"default_ttl_seconds,omitempty"`
	MaxTtlSeconds      *int                                                 `json:"max_ttl_seconds,omitempty" url:"max_ttl_seconds,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetHost() string {
	if u == nil {
		return ""
	}
	return u.Host
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetPort() *int {
	if u == nil {
		return nil
	}
	return u.Port
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetDatabase() string {
	if u == nil {
		return ""
	}
	return u.Database
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetSuperuser() *UpdateDynamicSecretEngineRequestConfigZeroSuperuser {
	if u == nil {
		return nil
	}
	return u.Superuser
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetCreationStatements() []string {
	if u == nil {
		return nil
	}
	return u.CreationStatements
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetDefaultTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.DefaultTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetMaxTtlSeconds() *int {
	if u == nil {
		return nil
	}
	return u.MaxTtlSeconds
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigZero
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigZero(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigZero) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequestConfigZeroSuperuser struct {
	Username string `json:"username" url:"username"`
	Password string `json:"password" url:"password"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateDynamicSecretEngineRequestConfigZeroSuperuser) GetUsername() string {
	if u == nil {
		return ""
	}
	return u.Username
}

func (u *UpdateDynamicSecretEngineRequestConfigZeroSuperuser) GetPassword() string {
	if u == nil {
		return ""
	}
	return u.Password
}

func (u *UpdateDynamicSecretEngineRequestConfigZeroSuperuser) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateDynamicSecretEngineRequestConfigZeroSuperuser) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateDynamicSecretEngineRequestConfigZeroSuperuser
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateDynamicSecretEngineRequestConfigZeroSuperuser(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateDynamicSecretEngineRequestConfigZeroSuperuser) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UpdateDynamicSecretEngineRequest struct {
	Name    *string                                 `json:"name,omitempty" url:"-"`
	Config  *UpdateDynamicSecretEngineRequestConfig `json:"config,omitempty" url:"-"`
	Enabled *bool                                   `json:"enabled,omitempty" url:"-"`
}
