// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type BreakGlassDetachOrgKmsRequest struct {
	EnvSyncPlatformToken string `json:"-" url:"-"`
}

type CreateOrgKmsCredentialRequest struct {
	Key         string  `json:"key" url:"-"`
	Value       string  `json:"value" url:"-"`
	Description *string `json:"description,omitempty" url:"-"`
}

type OrgKmsAppKeyInfo struct {
	AppId           string  `json:"app_id" url:"app_id"`
	Name            string  `json:"name" url:"name"`
	KeyVersionId    *string `json:"key_version_id,omitempty" url:"key_version_id,omitempty"`
	Version         *int    `json:"version,omitempty" url:"version,omitempty"`
	EncryptionCount *int    `json:"encryption_count,omitempty" url:"encryption_count,omitempty"`
	MaxEncryptions  *int    `json:"max_encryptions,omitempty" url:"max_encryptions,omitempty"`
	Status          string  `json:"status" url:"status"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsAppKeyInfo) GetAppId() string {
	if o == nil {
		return ""
	}
	return o.AppId
}

func (o *OrgKmsAppKeyInfo) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrgKmsAppKeyInfo) GetKeyVersionId() *string {
	if o == nil {
		return nil
	}
	return o.KeyVersionId
}

func (o *OrgKmsAppKeyInfo) GetVersion() *int {
	if o == nil {
		return nil
	}
	return o.Version
}

func (o *OrgKmsAppKeyInfo) GetEncryptionCount() *int {
	if o == nil {
		return nil
	}
	return o.EncryptionCount
}

func (o *OrgKmsAppKeyInfo) GetMaxEncryptions() *int {
	if o == nil {
		return nil
	}
	return o.MaxEncryptions
}

func (o *OrgKmsAppKeyInfo) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgKmsAppKeyInfo) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsAppKeyInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsAppKeyInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsAppKeyInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsAppKeyInfo) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsAppsResponse struct {
	Apps []*OrgKmsAppKeyInfo `json:"apps" url:"apps"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsAppsResponse) GetApps() []*OrgKmsAppKeyInfo {
	if o == nil {
		return nil
	}
	return o.Apps
}

func (o *OrgKmsAppsResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsAppsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsAppsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsAppsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsAppsResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsConfigResponse struct {
	OrgId              string                      `json:"org_id" url:"org_id"`
	Source             OrgKmsConfigResponseSource  `json:"source" url:"source"`
	Status             OrgKmsConfigResponseStatus  `json:"status" url:"status"`
	KeyRef             *string                     `json:"key_ref,omitempty" url:"key_ref,omitempty"`
	Region             *string                     `json:"region,omitempty" url:"region,omitempty"`
	CredentialSecretId *string                     `json:"credential_secret_id,omitempty" url:"credential_secret_id,omitempty"`
	KekVersion         int                         `json:"kek_version" url:"kek_version"`
	LastVerifiedAt     *string                     `json:"last_verified_at,omitempty" url:"last_verified_at,omitempty"`
	LastError          *string                     `json:"last_error,omitempty" url:"last_error,omitempty"`
	Implicit           bool                        `json:"implicit" url:"implicit"`
	Credentials        []*OrgKmsCredentialResponse `json:"credentials,omitempty" url:"credentials,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsConfigResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgKmsConfigResponse) GetSource() OrgKmsConfigResponseSource {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *OrgKmsConfigResponse) GetStatus() OrgKmsConfigResponseStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgKmsConfigResponse) GetKeyRef() *string {
	if o == nil {
		return nil
	}
	return o.KeyRef
}

func (o *OrgKmsConfigResponse) GetRegion() *string {
	if o == nil {
		return nil
	}
	return o.Region
}

func (o *OrgKmsConfigResponse) GetCredentialSecretId() *string {
	if o == nil {
		return nil
	}
	return o.CredentialSecretId
}

func (o *OrgKmsConfigResponse) GetKekVersion() int {
	if o == nil {
		return 0
	}
	return o.KekVersion
}

func (o *OrgKmsConfigResponse) GetLastVerifiedAt() *string {
	if o == nil {
		return nil
	}
	return o.LastVerifiedAt
}

func (o *OrgKmsConfigResponse) GetLastError() *string {
	if o == nil {
		return nil
	}
	return o.LastError
}

func (o *OrgKmsConfigResponse) GetImplicit() bool {
	if o == nil {
		return false
	}
	return o.Implicit
}

func (o *OrgKmsConfigResponse) GetCredentials() []*OrgKmsCredentialResponse {
	if o == nil {
		return nil
	}
	return o.Credentials
}

func (o *OrgKmsConfigResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsConfigResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsConfigResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsConfigResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsConfigResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsConfigResponseSource string

const (
	OrgKmsConfigResponseSourceManaged OrgKmsConfigResponseSource = "managed"
	OrgKmsConfigResponseSourceAwsKms  OrgKmsConfigResponseSource = "aws-kms"
	OrgKmsConfigResponseSourceGcpKms  OrgKmsConfigResponseSource = "gcp-kms"
	OrgKmsConfigResponseSourceAzureKv OrgKmsConfigResponseSource = "azure-kv"
)

func NewOrgKmsConfigResponseSourceFromString(s string) (OrgKmsConfigResponseSource, error) {
	switch s {
	case "managed":
		return OrgKmsConfigResponseSourceManaged, nil
	case "aws-kms":
		return OrgKmsConfigResponseSourceAwsKms, nil
	case "gcp-kms":
		return OrgKmsConfigResponseSourceGcpKms, nil
	case "azure-kv":
		return OrgKmsConfigResponseSourceAzureKv, nil
	}
	var t OrgKmsConfigResponseSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsConfigResponseSource) Ptr() *OrgKmsConfigResponseSource {
	return &o
}

type OrgKmsConfigResponseStatus string

const (
	OrgKmsConfigResponseStatusActive      OrgKmsConfigResponseStatus = "active"
	OrgKmsConfigResponseStatusPending     OrgKmsConfigResponseStatus = "pending"
	OrgKmsConfigResponseStatusRotating    OrgKmsConfigResponseStatus = "rotating"
	OrgKmsConfigResponseStatusUnavailable OrgKmsConfigResponseStatus = "unavailable"
	OrgKmsConfigResponseStatusDisabled    OrgKmsConfigResponseStatus = "disabled"
)

func NewOrgKmsConfigResponseStatusFromString(s string) (OrgKmsConfigResponseStatus, error) {
	switch s {
	case "active":
		return OrgKmsConfigResponseStatusActive, nil
	case "pending":
		return OrgKmsConfigResponseStatusPending, nil
	case "rotating":
		return OrgKmsConfigResponseStatusRotating, nil
	case "unavailable":
		return OrgKmsConfigResponseStatusUnavailable, nil
	case "disabled":
		return OrgKmsConfigResponseStatusDisabled, nil
	}
	var t OrgKmsConfigResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsConfigResponseStatus) Ptr() *OrgKmsConfigResponseStatus {
	return &o
}

type OrgKmsCredentialResponse struct {
	Id          string  `json:"id" url:"id"`
	OrgId       string  `json:"org_id" url:"org_id"`
	Key         string  `json:"key" url:"key"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	Configured  bool    `json:"configured" url:"configured"`
	CreatedAt   string  `json:"created_at" url:"created_at"`
	UpdatedAt   string  `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsCredentialResponse) GetId() string {
	if o == nil {
		return ""
	}
	return o.Id
}

func (o *OrgKmsCredentialResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgKmsCredentialResponse) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *OrgKmsCredentialResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OrgKmsCredentialResponse) GetConfigured() bool {
	if o == nil {
		return false
	}
	return o.Configured
}

func (o *OrgKmsCredentialResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *OrgKmsCredentialResponse) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *OrgKmsCredentialResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsCredentialResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsCredentialResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsCredentialResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsCredentialResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsJobResponse struct {
	Id           string                  `json:"id" url:"id"`
	OrgId        string                  `json:"org_id" url:"org_id"`
	AppId        *string                 `json:"app_id,omitempty" url:"app_id,omitempty"`
	Kind         OrgKmsJobResponseKind   `json:"kind" url:"kind"`
	Status       OrgKmsJobResponseStatus `json:"status" url:"status"`
	Progress     map[string]interface{}  `json:"progress" url:"progress"`
	ErrorMessage *string                 `json:"error_message,omitempty" url:"error_message,omitempty"`
	CreatedBy    *string                 `json:"created_by,omitempty" url:"created_by,omitempty"`
	CreatedAt    string                  `json:"created_at" url:"created_at"`
	UpdatedAt    string                  `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsJobResponse) GetId() string {
	if o == nil {
		return ""
	}
	return o.Id
}

func (o *OrgKmsJobResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgKmsJobResponse) GetAppId() *string {
	if o == nil {
		return nil
	}
	return o.AppId
}

func (o *OrgKmsJobResponse) GetKind() OrgKmsJobResponseKind {
	if o == nil {
		return ""
	}
	return o.Kind
}

func (o *OrgKmsJobResponse) GetStatus() OrgKmsJobResponseStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgKmsJobResponse) GetProgress() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Progress
}

func (o *OrgKmsJobResponse) GetErrorMessage() *string {
	if o == nil {
		return nil
	}
	return o.ErrorMessage
}

func (o *OrgKmsJobResponse) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *OrgKmsJobResponse) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *OrgKmsJobResponse) GetUpdatedAt() string {
	if o == nil {
		return ""
	}
	return o.UpdatedAt
}

func (o *OrgKmsJobResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsJobResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsJobResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsJobResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsJobResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsJobResponseKind string

const (
	OrgKmsJobResponseKindKekRewrap     OrgKmsJobResponseKind = "kek_rewrap"
	OrgKmsJobResponseKindDekRewrap     OrgKmsJobResponseKind = "dek_rewrap"
	OrgKmsJobResponseKindDetachManaged OrgKmsJobResponseKind = "detach_managed"
)

func NewOrgKmsJobResponseKindFromString(s string) (OrgKmsJobResponseKind, error) {
	switch s {
	case "kek_rewrap":
		return OrgKmsJobResponseKindKekRewrap, nil
	case "dek_rewrap":
		return OrgKmsJobResponseKindDekRewrap, nil
	case "detach_managed":
		return OrgKmsJobResponseKindDetachManaged, nil
	}
	var t OrgKmsJobResponseKind
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsJobResponseKind) Ptr() *OrgKmsJobResponseKind {
	return &o
}

type OrgKmsJobResponseStatus string

const (
	OrgKmsJobResponseStatusPending   OrgKmsJobResponseStatus = "pending"
	OrgKmsJobResponseStatusRunning   OrgKmsJobResponseStatus = "running"
	OrgKmsJobResponseStatusSucceeded OrgKmsJobResponseStatus = "succeeded"
	OrgKmsJobResponseStatusFailed    OrgKmsJobResponseStatus = "failed"
)

func NewOrgKmsJobResponseStatusFromString(s string) (OrgKmsJobResponseStatus, error) {
	switch s {
	case "pending":
		return OrgKmsJobResponseStatusPending, nil
	case "running":
		return OrgKmsJobResponseStatusRunning, nil
	case "succeeded":
		return OrgKmsJobResponseStatusSucceeded, nil
	case "failed":
		return OrgKmsJobResponseStatusFailed, nil
	}
	var t OrgKmsJobResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsJobResponseStatus) Ptr() *OrgKmsJobResponseStatus {
	return &o
}

type OrgKmsVerifyResponse struct {
	Ok             bool                       `json:"ok" url:"ok"`
	Source         OrgKmsVerifyResponseSource `json:"source" url:"source"`
	Status         OrgKmsVerifyResponseStatus `json:"status" url:"status"`
	LastVerifiedAt string                     `json:"last_verified_at" url:"last_verified_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgKmsVerifyResponse) GetOk() bool {
	if o == nil {
		return false
	}
	return o.Ok
}

func (o *OrgKmsVerifyResponse) GetSource() OrgKmsVerifyResponseSource {
	if o == nil {
		return ""
	}
	return o.Source
}

func (o *OrgKmsVerifyResponse) GetStatus() OrgKmsVerifyResponseStatus {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *OrgKmsVerifyResponse) GetLastVerifiedAt() string {
	if o == nil {
		return ""
	}
	return o.LastVerifiedAt
}

func (o *OrgKmsVerifyResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgKmsVerifyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgKmsVerifyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgKmsVerifyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgKmsVerifyResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OrgKmsVerifyResponseSource string

const (
	OrgKmsVerifyResponseSourceManaged OrgKmsVerifyResponseSource = "managed"
	OrgKmsVerifyResponseSourceAwsKms  OrgKmsVerifyResponseSource = "aws-kms"
	OrgKmsVerifyResponseSourceGcpKms  OrgKmsVerifyResponseSource = "gcp-kms"
	OrgKmsVerifyResponseSourceAzureKv OrgKmsVerifyResponseSource = "azure-kv"
)

func NewOrgKmsVerifyResponseSourceFromString(s string) (OrgKmsVerifyResponseSource, error) {
	switch s {
	case "managed":
		return OrgKmsVerifyResponseSourceManaged, nil
	case "aws-kms":
		return OrgKmsVerifyResponseSourceAwsKms, nil
	case "gcp-kms":
		return OrgKmsVerifyResponseSourceGcpKms, nil
	case "azure-kv":
		return OrgKmsVerifyResponseSourceAzureKv, nil
	}
	var t OrgKmsVerifyResponseSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsVerifyResponseSource) Ptr() *OrgKmsVerifyResponseSource {
	return &o
}

type OrgKmsVerifyResponseStatus string

const (
	OrgKmsVerifyResponseStatusActive      OrgKmsVerifyResponseStatus = "active"
	OrgKmsVerifyResponseStatusPending     OrgKmsVerifyResponseStatus = "pending"
	OrgKmsVerifyResponseStatusRotating    OrgKmsVerifyResponseStatus = "rotating"
	OrgKmsVerifyResponseStatusUnavailable OrgKmsVerifyResponseStatus = "unavailable"
	OrgKmsVerifyResponseStatusDisabled    OrgKmsVerifyResponseStatus = "disabled"
)

func NewOrgKmsVerifyResponseStatusFromString(s string) (OrgKmsVerifyResponseStatus, error) {
	switch s {
	case "active":
		return OrgKmsVerifyResponseStatusActive, nil
	case "pending":
		return OrgKmsVerifyResponseStatusPending, nil
	case "rotating":
		return OrgKmsVerifyResponseStatusRotating, nil
	case "unavailable":
		return OrgKmsVerifyResponseStatusUnavailable, nil
	case "disabled":
		return OrgKmsVerifyResponseStatusDisabled, nil
	}
	var t OrgKmsVerifyResponseStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o OrgKmsVerifyResponseStatus) Ptr() *OrgKmsVerifyResponseStatus {
	return &o
}

type UpdateOrgKmsConfigRequestSource string

const (
	UpdateOrgKmsConfigRequestSourceManaged UpdateOrgKmsConfigRequestSource = "managed"
	UpdateOrgKmsConfigRequestSourceAwsKms  UpdateOrgKmsConfigRequestSource = "aws-kms"
	UpdateOrgKmsConfigRequestSourceGcpKms  UpdateOrgKmsConfigRequestSource = "gcp-kms"
	UpdateOrgKmsConfigRequestSourceAzureKv UpdateOrgKmsConfigRequestSource = "azure-kv"
)

func NewUpdateOrgKmsConfigRequestSourceFromString(s string) (UpdateOrgKmsConfigRequestSource, error) {
	switch s {
	case "managed":
		return UpdateOrgKmsConfigRequestSourceManaged, nil
	case "aws-kms":
		return UpdateOrgKmsConfigRequestSourceAwsKms, nil
	case "gcp-kms":
		return UpdateOrgKmsConfigRequestSourceGcpKms, nil
	case "azure-kv":
		return UpdateOrgKmsConfigRequestSourceAzureKv, nil
	}
	var t UpdateOrgKmsConfigRequestSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateOrgKmsConfigRequestSource) Ptr() *UpdateOrgKmsConfigRequestSource {
	return &u
}

type UpdateOrgKmsConfigRequest struct {
	Source             UpdateOrgKmsConfigRequestSource `json:"source" url:"-"`
	KeyRef             *string                         `json:"key_ref,omitempty" url:"-"`
	Region             *string                         `json:"region,omitempty" url:"-"`
	CredentialSecretId *string                         `json:"credential_secret_id,omitempty" url:"-"`
}
