// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type DeleteOrgFeatureGrantRequest struct {
	EnvSyncPlatformToken string `json:"-" url:"-"`
}

type GetOrgFeatureGrantRequest struct {
	EnvSyncPlatformToken string `json:"-" url:"-"`
}

type PutOrgFeatureGrantRequest struct {
	EnvSyncPlatformToken string                           `json:"-" url:"-"`
	Plan                 *PutOrgFeatureGrantRequestPlan   `json:"plan,omitempty" url:"-"`
	Features             []string                         `json:"features,omitempty" url:"-"`
	OverlayFeatures      []string                         `json:"overlay_features,omitempty" url:"-"`
	Source               *PutOrgFeatureGrantRequestSource `json:"source,omitempty" url:"-"`
	UpdatedBy            *string                          `json:"updated_by,omitempty" url:"-"`
}

type OrgFeatureGrantResponse struct {
	OrgId           string   `json:"org_id" url:"org_id"`
	Unrestricted    bool     `json:"unrestricted" url:"unrestricted"`
	Plan            *string  `json:"plan,omitempty" url:"plan,omitempty"`
	Features        []string `json:"features" url:"features"`
	OverlayFeatures []string `json:"overlay_features" url:"overlay_features"`
	Source          *string  `json:"source,omitempty" url:"source,omitempty"`
	UpdatedBy       *string  `json:"updated_by,omitempty" url:"updated_by,omitempty"`
	CreatedAt       *string  `json:"created_at,omitempty" url:"created_at,omitempty"`
	UpdatedAt       *string  `json:"updated_at,omitempty" url:"updated_at,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (o *OrgFeatureGrantResponse) GetOrgId() string {
	if o == nil {
		return ""
	}
	return o.OrgId
}

func (o *OrgFeatureGrantResponse) GetUnrestricted() bool {
	if o == nil {
		return false
	}
	return o.Unrestricted
}

func (o *OrgFeatureGrantResponse) GetPlan() *string {
	if o == nil {
		return nil
	}
	return o.Plan
}

func (o *OrgFeatureGrantResponse) GetFeatures() []string {
	if o == nil {
		return nil
	}
	return o.Features
}

func (o *OrgFeatureGrantResponse) GetOverlayFeatures() []string {
	if o == nil {
		return nil
	}
	return o.OverlayFeatures
}

func (o *OrgFeatureGrantResponse) GetSource() *string {
	if o == nil {
		return nil
	}
	return o.Source
}

func (o *OrgFeatureGrantResponse) GetUpdatedBy() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedBy
}

func (o *OrgFeatureGrantResponse) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *OrgFeatureGrantResponse) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *OrgFeatureGrantResponse) GetExtraProperties() map[string]interface{} {
	return o.extraProperties
}

func (o *OrgFeatureGrantResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler OrgFeatureGrantResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*o = OrgFeatureGrantResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *o)
	if err != nil {
		return err
	}
	o.extraProperties = extraProperties
	o.rawJSON = json.RawMessage(data)
	return nil
}

func (o *OrgFeatureGrantResponse) String() string {
	if len(o.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(o.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type PutOrgFeatureGrantRequestPlan string

const (
	PutOrgFeatureGrantRequestPlanDeveloper  PutOrgFeatureGrantRequestPlan = "developer"
	PutOrgFeatureGrantRequestPlanPlus       PutOrgFeatureGrantRequestPlan = "plus"
	PutOrgFeatureGrantRequestPlanEnterprise PutOrgFeatureGrantRequestPlan = "enterprise"
)

func NewPutOrgFeatureGrantRequestPlanFromString(s string) (PutOrgFeatureGrantRequestPlan, error) {
	switch s {
	case "developer":
		return PutOrgFeatureGrantRequestPlanDeveloper, nil
	case "plus":
		return PutOrgFeatureGrantRequestPlanPlus, nil
	case "enterprise":
		return PutOrgFeatureGrantRequestPlanEnterprise, nil
	}
	var t PutOrgFeatureGrantRequestPlan
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PutOrgFeatureGrantRequestPlan) Ptr() *PutOrgFeatureGrantRequestPlan {
	return &p
}

type PutOrgFeatureGrantRequestSource string

const (
	PutOrgFeatureGrantRequestSourceBilling PutOrgFeatureGrantRequestSource = "billing"
	PutOrgFeatureGrantRequestSourceSupport PutOrgFeatureGrantRequestSource = "support"
	PutOrgFeatureGrantRequestSourceSeed    PutOrgFeatureGrantRequestSource = "seed"
)

func NewPutOrgFeatureGrantRequestSourceFromString(s string) (PutOrgFeatureGrantRequestSource, error) {
	switch s {
	case "billing":
		return PutOrgFeatureGrantRequestSourceBilling, nil
	case "support":
		return PutOrgFeatureGrantRequestSourceSupport, nil
	case "seed":
		return PutOrgFeatureGrantRequestSourceSeed, nil
	}
	var t PutOrgFeatureGrantRequestSource
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PutOrgFeatureGrantRequestSource) Ptr() *PutOrgFeatureGrantRequestSource {
	return &p
}
