// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type CreateRotationPolicyRequest struct {
	AppId             string                                `json:"app_id" url:"-"`
	EnvTypeId         string                                `json:"env_type_id" url:"-"`
	VariableKey       string                                `json:"variable_key" url:"-"`
	EngineType        CreateRotationPolicyRequestEngineType `json:"engine_type" url:"-"`
	ScheduleCron      string                                `json:"schedule_cron" url:"-"`
	DualWindowMinutes *int                                  `json:"dual_window_minutes,omitempty" url:"-"`
	Enabled           *bool                                 `json:"enabled,omitempty" url:"-"`
	ConnectionConfig  map[string]interface{}                `json:"connection_config,omitempty" url:"-"`
}

type GetRotationPoliciesRequest struct {
	AppId     *string                            `json:"-" url:"app_id,omitempty"`
	EnvTypeId *string                            `json:"-" url:"env_type_id,omitempty"`
	Enabled   *GetRotationPoliciesRequestEnabled `json:"-" url:"enabled,omitempty"`
}

type RevokeOldCredentialResponse struct {
	Message   string `json:"message" url:"message"`
	RevokedAt string `json:"revoked_at" url:"revoked_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RevokeOldCredentialResponse) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RevokeOldCredentialResponse) GetRevokedAt() string {
	if r == nil {
		return ""
	}
	return r.RevokedAt
}

func (r *RevokeOldCredentialResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RevokeOldCredentialResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RevokeOldCredentialResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RevokeOldCredentialResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RevokeOldCredentialResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RotationPoliciesResponse = []*RotationPolicyResponse

type RotationPolicyResponse struct {
	Id                string                           `json:"id" url:"id"`
	OrgId             string                           `json:"org_id" url:"org_id"`
	AppId             string                           `json:"app_id" url:"app_id"`
	EnvTypeId         string                           `json:"env_type_id" url:"env_type_id"`
	VariableKey       string                           `json:"variable_key" url:"variable_key"`
	EngineType        RotationPolicyResponseEngineType `json:"engine_type" url:"engine_type"`
	ScheduleCron      string                           `json:"schedule_cron" url:"schedule_cron"`
	DualWindowMinutes float64                          `json:"dual_window_minutes" url:"dual_window_minutes"`
	Enabled           bool                             `json:"enabled" url:"enabled"`
	LastRotatedAt     *string                          `json:"last_rotated_at,omitempty" url:"last_rotated_at,omitempty"`
	NextRotationAt    *string                          `json:"next_rotation_at,omitempty" url:"next_rotation_at,omitempty"`
	CreatedAt         string                           `json:"created_at" url:"created_at"`
	UpdatedAt         string                           `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RotationPolicyResponse) GetId() string {
	if r == nil {
		return ""
	}
	return r.Id
}

func (r *RotationPolicyResponse) GetOrgId() string {
	if r == nil {
		return ""
	}
	return r.OrgId
}

func (r *RotationPolicyResponse) GetAppId() string {
	if r == nil {
		return ""
	}
	return r.AppId
}

func (r *RotationPolicyResponse) GetEnvTypeId() string {
	if r == nil {
		return ""
	}
	return r.EnvTypeId
}

func (r *RotationPolicyResponse) GetVariableKey() string {
	if r == nil {
		return ""
	}
	return r.VariableKey
}

func (r *RotationPolicyResponse) GetEngineType() RotationPolicyResponseEngineType {
	if r == nil {
		return ""
	}
	return r.EngineType
}

func (r *RotationPolicyResponse) GetScheduleCron() string {
	if r == nil {
		return ""
	}
	return r.ScheduleCron
}

func (r *RotationPolicyResponse) GetDualWindowMinutes() float64 {
	if r == nil {
		return 0
	}
	return r.DualWindowMinutes
}

func (r *RotationPolicyResponse) GetEnabled() bool {
	if r == nil {
		return false
	}
	return r.Enabled
}

func (r *RotationPolicyResponse) GetLastRotatedAt() *string {
	if r == nil {
		return nil
	}
	return r.LastRotatedAt
}

func (r *RotationPolicyResponse) GetNextRotationAt() *string {
	if r == nil {
		return nil
	}
	return r.NextRotationAt
}

func (r *RotationPolicyResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RotationPolicyResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RotationPolicyResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RotationPolicyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RotationPolicyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RotationPolicyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RotationPolicyResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RotationPolicyResponseEngineType string

const (
	RotationPolicyResponseEngineTypePostgres          RotationPolicyResponseEngineType = "postgres"
	RotationPolicyResponseEngineTypeMysql             RotationPolicyResponseEngineType = "mysql"
	RotationPolicyResponseEngineTypeAwsIam            RotationPolicyResponseEngineType = "aws-iam"
	RotationPolicyResponseEngineTypeAzureSp           RotationPolicyResponseEngineType = "azure-sp"
	RotationPolicyResponseEngineTypeGcpServiceAccount RotationPolicyResponseEngineType = "gcp-service-account"
	RotationPolicyResponseEngineTypeCloudflarePages   RotationPolicyResponseEngineType = "cloudflare-pages"
	RotationPolicyResponseEngineTypeSendgrid          RotationPolicyResponseEngineType = "sendgrid"
	RotationPolicyResponseEngineTypeTwilio            RotationPolicyResponseEngineType = "twilio"
)

func NewRotationPolicyResponseEngineTypeFromString(s string) (RotationPolicyResponseEngineType, error) {
	switch s {
	case "postgres":
		return RotationPolicyResponseEngineTypePostgres, nil
	case "mysql":
		return RotationPolicyResponseEngineTypeMysql, nil
	case "aws-iam":
		return RotationPolicyResponseEngineTypeAwsIam, nil
	case "azure-sp":
		return RotationPolicyResponseEngineTypeAzureSp, nil
	case "gcp-service-account":
		return RotationPolicyResponseEngineTypeGcpServiceAccount, nil
	case "cloudflare-pages":
		return RotationPolicyResponseEngineTypeCloudflarePages, nil
	case "sendgrid":
		return RotationPolicyResponseEngineTypeSendgrid, nil
	case "twilio":
		return RotationPolicyResponseEngineTypeTwilio, nil
	}
	var t RotationPolicyResponseEngineType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (r RotationPolicyResponseEngineType) Ptr() *RotationPolicyResponseEngineType {
	return &r
}

type RotationStateResponse struct {
	Id                     string  `json:"id" url:"id"`
	RotationPolicyId       string  `json:"rotation_policy_id" url:"rotation_policy_id"`
	RotatedAt              string  `json:"rotated_at" url:"rotated_at"`
	OldCredentialExpiresAt string  `json:"old_credential_expires_at" url:"old_credential_expires_at"`
	OldCredentialRevoked   bool    `json:"old_credential_revoked" url:"old_credential_revoked"`
	RevokedAt              *string `json:"revoked_at,omitempty" url:"revoked_at,omitempty"`
	CreatedAt              string  `json:"created_at" url:"created_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RotationStateResponse) GetId() string {
	if r == nil {
		return ""
	}
	return r.Id
}

func (r *RotationStateResponse) GetRotationPolicyId() string {
	if r == nil {
		return ""
	}
	return r.RotationPolicyId
}

func (r *RotationStateResponse) GetRotatedAt() string {
	if r == nil {
		return ""
	}
	return r.RotatedAt
}

func (r *RotationStateResponse) GetOldCredentialExpiresAt() string {
	if r == nil {
		return ""
	}
	return r.OldCredentialExpiresAt
}

func (r *RotationStateResponse) GetOldCredentialRevoked() bool {
	if r == nil {
		return false
	}
	return r.OldCredentialRevoked
}

func (r *RotationStateResponse) GetRevokedAt() *string {
	if r == nil {
		return nil
	}
	return r.RevokedAt
}

func (r *RotationStateResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RotationStateResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RotationStateResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RotationStateResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RotationStateResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RotationStateResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RotationStatesResponse = []*RotationStateResponse

type TriggerRotationResponse struct {
	Message                string `json:"message" url:"message"`
	RotationStateId        string `json:"rotation_state_id" url:"rotation_state_id"`
	NewCredentialStored    bool   `json:"new_credential_stored" url:"new_credential_stored"`
	OldCredentialExpiresAt string `json:"old_credential_expires_at" url:"old_credential_expires_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (t *TriggerRotationResponse) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

func (t *TriggerRotationResponse) GetRotationStateId() string {
	if t == nil {
		return ""
	}
	return t.RotationStateId
}

func (t *TriggerRotationResponse) GetNewCredentialStored() bool {
	if t == nil {
		return false
	}
	return t.NewCredentialStored
}

func (t *TriggerRotationResponse) GetOldCredentialExpiresAt() string {
	if t == nil {
		return ""
	}
	return t.OldCredentialExpiresAt
}

func (t *TriggerRotationResponse) GetExtraProperties() map[string]interface{} {
	return t.extraProperties
}

func (t *TriggerRotationResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler TriggerRotationResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*t = TriggerRotationResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *t)
	if err != nil {
		return err
	}
	t.extraProperties = extraProperties
	t.rawJSON = json.RawMessage(data)
	return nil
}

func (t *TriggerRotationResponse) String() string {
	if len(t.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(t.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(t); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", t)
}

type CreateRotationPolicyRequestEngineType string

const (
	CreateRotationPolicyRequestEngineTypePostgres          CreateRotationPolicyRequestEngineType = "postgres"
	CreateRotationPolicyRequestEngineTypeMysql             CreateRotationPolicyRequestEngineType = "mysql"
	CreateRotationPolicyRequestEngineTypeAwsIam            CreateRotationPolicyRequestEngineType = "aws-iam"
	CreateRotationPolicyRequestEngineTypeAzureSp           CreateRotationPolicyRequestEngineType = "azure-sp"
	CreateRotationPolicyRequestEngineTypeGcpServiceAccount CreateRotationPolicyRequestEngineType = "gcp-service-account"
	CreateRotationPolicyRequestEngineTypeCloudflarePages   CreateRotationPolicyRequestEngineType = "cloudflare-pages"
	CreateRotationPolicyRequestEngineTypeSendgrid          CreateRotationPolicyRequestEngineType = "sendgrid"
	CreateRotationPolicyRequestEngineTypeTwilio            CreateRotationPolicyRequestEngineType = "twilio"
)

func NewCreateRotationPolicyRequestEngineTypeFromString(s string) (CreateRotationPolicyRequestEngineType, error) {
	switch s {
	case "postgres":
		return CreateRotationPolicyRequestEngineTypePostgres, nil
	case "mysql":
		return CreateRotationPolicyRequestEngineTypeMysql, nil
	case "aws-iam":
		return CreateRotationPolicyRequestEngineTypeAwsIam, nil
	case "azure-sp":
		return CreateRotationPolicyRequestEngineTypeAzureSp, nil
	case "gcp-service-account":
		return CreateRotationPolicyRequestEngineTypeGcpServiceAccount, nil
	case "cloudflare-pages":
		return CreateRotationPolicyRequestEngineTypeCloudflarePages, nil
	case "sendgrid":
		return CreateRotationPolicyRequestEngineTypeSendgrid, nil
	case "twilio":
		return CreateRotationPolicyRequestEngineTypeTwilio, nil
	}
	var t CreateRotationPolicyRequestEngineType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateRotationPolicyRequestEngineType) Ptr() *CreateRotationPolicyRequestEngineType {
	return &c
}

type GetRotationPoliciesRequestEnabled string

const (
	GetRotationPoliciesRequestEnabledTrue  GetRotationPoliciesRequestEnabled = "true"
	GetRotationPoliciesRequestEnabledFalse GetRotationPoliciesRequestEnabled = "false"
)

func NewGetRotationPoliciesRequestEnabledFromString(s string) (GetRotationPoliciesRequestEnabled, error) {
	switch s {
	case "true":
		return GetRotationPoliciesRequestEnabledTrue, nil
	case "false":
		return GetRotationPoliciesRequestEnabledFalse, nil
	}
	var t GetRotationPoliciesRequestEnabled
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetRotationPoliciesRequestEnabled) Ptr() *GetRotationPoliciesRequestEnabled {
	return &g
}

type UpdateRotationPolicyRequest struct {
	ScheduleCron      *string                `json:"schedule_cron,omitempty" url:"-"`
	DualWindowMinutes *int                   `json:"dual_window_minutes,omitempty" url:"-"`
	Enabled           *bool                  `json:"enabled,omitempty" url:"-"`
	ConnectionConfig  map[string]interface{} `json:"connection_config,omitempty" url:"-"`
}
