// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type CreateSamlProviderRequest struct {
	// SAML identity provider type
	ProviderType CreateSamlProviderRequestProviderType `json:"provider_type" url:"-"`
	// Human-readable name for this provider
	Name string `json:"name" url:"-"`
	// SAML entity ID (issuer) from the IdP metadata
	EntityId string `json:"entity_id" url:"-"`
	// IdP SSO login URL
	SsoUrl string `json:"sso_url" url:"-"`
	// IdP X.509 certificate (PEM format) for signature validation
	Certificate string `json:"certificate" url:"-"`
}

type SamlProviderResponse struct {
	Id           string                           `json:"id" url:"id"`
	OrgId        string                           `json:"org_id" url:"org_id"`
	ProviderType SamlProviderResponseProviderType `json:"provider_type" url:"provider_type"`
	Name         string                           `json:"name" url:"name"`
	EntityId     string                           `json:"entity_id" url:"entity_id"`
	SsoUrl       string                           `json:"sso_url" url:"sso_url"`
	Certificate  string                           `json:"certificate" url:"certificate"`
	Enabled      bool                             `json:"enabled" url:"enabled"`
	CreatedAt    string                           `json:"created_at" url:"created_at"`
	UpdatedAt    string                           `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SamlProviderResponse) GetId() string {
	if s == nil {
		return ""
	}
	return s.Id
}

func (s *SamlProviderResponse) GetOrgId() string {
	if s == nil {
		return ""
	}
	return s.OrgId
}

func (s *SamlProviderResponse) GetProviderType() SamlProviderResponseProviderType {
	if s == nil {
		return ""
	}
	return s.ProviderType
}

func (s *SamlProviderResponse) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *SamlProviderResponse) GetEntityId() string {
	if s == nil {
		return ""
	}
	return s.EntityId
}

func (s *SamlProviderResponse) GetSsoUrl() string {
	if s == nil {
		return ""
	}
	return s.SsoUrl
}

func (s *SamlProviderResponse) GetCertificate() string {
	if s == nil {
		return ""
	}
	return s.Certificate
}

func (s *SamlProviderResponse) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *SamlProviderResponse) GetCreatedAt() string {
	if s == nil {
		return ""
	}
	return s.CreatedAt
}

func (s *SamlProviderResponse) GetUpdatedAt() string {
	if s == nil {
		return ""
	}
	return s.UpdatedAt
}

func (s *SamlProviderResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SamlProviderResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SamlProviderResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SamlProviderResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SamlProviderResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SamlProviderResponseProviderType string

const (
	SamlProviderResponseProviderTypeOkta            SamlProviderResponseProviderType = "okta"
	SamlProviderResponseProviderTypeOnelogin        SamlProviderResponseProviderType = "onelogin"
	SamlProviderResponseProviderTypeAzureAd         SamlProviderResponseProviderType = "azure-ad"
	SamlProviderResponseProviderTypeGoogleWorkspace SamlProviderResponseProviderType = "google-workspace"
	SamlProviderResponseProviderTypeDuo             SamlProviderResponseProviderType = "duo"
	SamlProviderResponseProviderTypeRippling        SamlProviderResponseProviderType = "rippling"
	SamlProviderResponseProviderTypeOracle          SamlProviderResponseProviderType = "oracle"
	SamlProviderResponseProviderTypePingIdentity    SamlProviderResponseProviderType = "ping-identity"
)

func NewSamlProviderResponseProviderTypeFromString(s string) (SamlProviderResponseProviderType, error) {
	switch s {
	case "okta":
		return SamlProviderResponseProviderTypeOkta, nil
	case "onelogin":
		return SamlProviderResponseProviderTypeOnelogin, nil
	case "azure-ad":
		return SamlProviderResponseProviderTypeAzureAd, nil
	case "google-workspace":
		return SamlProviderResponseProviderTypeGoogleWorkspace, nil
	case "duo":
		return SamlProviderResponseProviderTypeDuo, nil
	case "rippling":
		return SamlProviderResponseProviderTypeRippling, nil
	case "oracle":
		return SamlProviderResponseProviderTypeOracle, nil
	case "ping-identity":
		return SamlProviderResponseProviderTypePingIdentity, nil
	}
	var t SamlProviderResponseProviderType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SamlProviderResponseProviderType) Ptr() *SamlProviderResponseProviderType {
	return &s
}

type SamlProvidersResponse = []*SamlProviderResponse

// SAML identity provider type
type CreateSamlProviderRequestProviderType string

const (
	CreateSamlProviderRequestProviderTypeOkta            CreateSamlProviderRequestProviderType = "okta"
	CreateSamlProviderRequestProviderTypeOnelogin        CreateSamlProviderRequestProviderType = "onelogin"
	CreateSamlProviderRequestProviderTypeAzureAd         CreateSamlProviderRequestProviderType = "azure-ad"
	CreateSamlProviderRequestProviderTypeGoogleWorkspace CreateSamlProviderRequestProviderType = "google-workspace"
	CreateSamlProviderRequestProviderTypeDuo             CreateSamlProviderRequestProviderType = "duo"
	CreateSamlProviderRequestProviderTypeRippling        CreateSamlProviderRequestProviderType = "rippling"
	CreateSamlProviderRequestProviderTypeOracle          CreateSamlProviderRequestProviderType = "oracle"
	CreateSamlProviderRequestProviderTypePingIdentity    CreateSamlProviderRequestProviderType = "ping-identity"
)

func NewCreateSamlProviderRequestProviderTypeFromString(s string) (CreateSamlProviderRequestProviderType, error) {
	switch s {
	case "okta":
		return CreateSamlProviderRequestProviderTypeOkta, nil
	case "onelogin":
		return CreateSamlProviderRequestProviderTypeOnelogin, nil
	case "azure-ad":
		return CreateSamlProviderRequestProviderTypeAzureAd, nil
	case "google-workspace":
		return CreateSamlProviderRequestProviderTypeGoogleWorkspace, nil
	case "duo":
		return CreateSamlProviderRequestProviderTypeDuo, nil
	case "rippling":
		return CreateSamlProviderRequestProviderTypeRippling, nil
	case "oracle":
		return CreateSamlProviderRequestProviderTypeOracle, nil
	case "ping-identity":
		return CreateSamlProviderRequestProviderTypePingIdentity, nil
	}
	var t CreateSamlProviderRequestProviderType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSamlProviderRequestProviderType) Ptr() *CreateSamlProviderRequestProviderType {
	return &c
}

type UpdateSamlProviderRequest struct {
	Name        *string `json:"name,omitempty" url:"-"`
	EntityId    *string `json:"entity_id,omitempty" url:"-"`
	SsoUrl      *string `json:"sso_url,omitempty" url:"-"`
	Certificate *string `json:"certificate,omitempty" url:"-"`
	Enabled     *bool   `json:"enabled,omitempty" url:"-"`
}
