// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/EnvSync-Cloud/envsync/sdks/envsync-go-sdk/sdk/internal"
)

type EffectivePermissionsResponse struct {
	CanView              bool `json:"can_view" url:"can_view"`
	CanEdit              bool `json:"can_edit" url:"can_edit"`
	HaveApiAccess        bool `json:"have_api_access" url:"have_api_access"`
	HaveBillingOptions   bool `json:"have_billing_options" url:"have_billing_options"`
	HaveWebhookAccess    bool `json:"have_webhook_access" url:"have_webhook_access"`
	IsAdmin              bool `json:"is_admin" url:"is_admin"`
	IsMaster             bool `json:"is_master" url:"is_master"`
	CanManageRoles       bool `json:"can_manage_roles" url:"can_manage_roles"`
	CanManageUsers       bool `json:"can_manage_users" url:"can_manage_users"`
	CanManageApps        bool `json:"can_manage_apps" url:"can_manage_apps"`
	CanManageApiKeys     bool `json:"can_manage_api_keys" url:"can_manage_api_keys"`
	CanManageWebhooks    bool `json:"can_manage_webhooks" url:"can_manage_webhooks"`
	CanViewAuditLogs     bool `json:"can_view_audit_logs" url:"can_view_audit_logs"`
	CanManageOrgSettings bool `json:"can_manage_org_settings" url:"can_manage_org_settings"`
	CanManageInvites     bool `json:"can_manage_invites" url:"can_manage_invites"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *EffectivePermissionsResponse) GetCanView() bool {
	if e == nil {
		return false
	}
	return e.CanView
}

func (e *EffectivePermissionsResponse) GetCanEdit() bool {
	if e == nil {
		return false
	}
	return e.CanEdit
}

func (e *EffectivePermissionsResponse) GetHaveApiAccess() bool {
	if e == nil {
		return false
	}
	return e.HaveApiAccess
}

func (e *EffectivePermissionsResponse) GetHaveBillingOptions() bool {
	if e == nil {
		return false
	}
	return e.HaveBillingOptions
}

func (e *EffectivePermissionsResponse) GetHaveWebhookAccess() bool {
	if e == nil {
		return false
	}
	return e.HaveWebhookAccess
}

func (e *EffectivePermissionsResponse) GetIsAdmin() bool {
	if e == nil {
		return false
	}
	return e.IsAdmin
}

func (e *EffectivePermissionsResponse) GetIsMaster() bool {
	if e == nil {
		return false
	}
	return e.IsMaster
}

func (e *EffectivePermissionsResponse) GetCanManageRoles() bool {
	if e == nil {
		return false
	}
	return e.CanManageRoles
}

func (e *EffectivePermissionsResponse) GetCanManageUsers() bool {
	if e == nil {
		return false
	}
	return e.CanManageUsers
}

func (e *EffectivePermissionsResponse) GetCanManageApps() bool {
	if e == nil {
		return false
	}
	return e.CanManageApps
}

func (e *EffectivePermissionsResponse) GetCanManageApiKeys() bool {
	if e == nil {
		return false
	}
	return e.CanManageApiKeys
}

func (e *EffectivePermissionsResponse) GetCanManageWebhooks() bool {
	if e == nil {
		return false
	}
	return e.CanManageWebhooks
}

func (e *EffectivePermissionsResponse) GetCanViewAuditLogs() bool {
	if e == nil {
		return false
	}
	return e.CanViewAuditLogs
}

func (e *EffectivePermissionsResponse) GetCanManageOrgSettings() bool {
	if e == nil {
		return false
	}
	return e.CanManageOrgSettings
}

func (e *EffectivePermissionsResponse) GetCanManageInvites() bool {
	if e == nil {
		return false
	}
	return e.CanManageInvites
}

func (e *EffectivePermissionsResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *EffectivePermissionsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler EffectivePermissionsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = EffectivePermissionsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *EffectivePermissionsResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type RoleResponse struct {
	Id                 string  `json:"id" url:"id"`
	Name               string  `json:"name" url:"name"`
	OrgId              string  `json:"org_id" url:"org_id"`
	CanEdit            bool    `json:"can_edit" url:"can_edit"`
	CanView            bool    `json:"can_view" url:"can_view"`
	HaveApiAccess      bool    `json:"have_api_access" url:"have_api_access"`
	HaveBillingOptions bool    `json:"have_billing_options" url:"have_billing_options"`
	HaveWebhookAccess  bool    `json:"have_webhook_access" url:"have_webhook_access"`
	HaveGpgAccess      bool    `json:"have_gpg_access" url:"have_gpg_access"`
	HaveCertAccess     bool    `json:"have_cert_access" url:"have_cert_access"`
	HaveAuditAccess    bool    `json:"have_audit_access" url:"have_audit_access"`
	Color              *string `json:"color,omitempty" url:"color,omitempty"`
	IsAdmin            bool    `json:"is_admin" url:"is_admin"`
	IsMaster           bool    `json:"is_master" url:"is_master"`
	CreatedAt          string  `json:"created_at" url:"created_at"`
	UpdatedAt          string  `json:"updated_at" url:"updated_at"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RoleResponse) GetId() string {
	if r == nil {
		return ""
	}
	return r.Id
}

func (r *RoleResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RoleResponse) GetOrgId() string {
	if r == nil {
		return ""
	}
	return r.OrgId
}

func (r *RoleResponse) GetCanEdit() bool {
	if r == nil {
		return false
	}
	return r.CanEdit
}

func (r *RoleResponse) GetCanView() bool {
	if r == nil {
		return false
	}
	return r.CanView
}

func (r *RoleResponse) GetHaveApiAccess() bool {
	if r == nil {
		return false
	}
	return r.HaveApiAccess
}

func (r *RoleResponse) GetHaveBillingOptions() bool {
	if r == nil {
		return false
	}
	return r.HaveBillingOptions
}

func (r *RoleResponse) GetHaveWebhookAccess() bool {
	if r == nil {
		return false
	}
	return r.HaveWebhookAccess
}

func (r *RoleResponse) GetHaveGpgAccess() bool {
	if r == nil {
		return false
	}
	return r.HaveGpgAccess
}

func (r *RoleResponse) GetHaveCertAccess() bool {
	if r == nil {
		return false
	}
	return r.HaveCertAccess
}

func (r *RoleResponse) GetHaveAuditAccess() bool {
	if r == nil {
		return false
	}
	return r.HaveAuditAccess
}

func (r *RoleResponse) GetColor() *string {
	if r == nil {
		return nil
	}
	return r.Color
}

func (r *RoleResponse) GetIsAdmin() bool {
	if r == nil {
		return false
	}
	return r.IsAdmin
}

func (r *RoleResponse) GetIsMaster() bool {
	if r == nil {
		return false
	}
	return r.IsMaster
}

func (r *RoleResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RoleResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RoleResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RoleResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RoleResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RoleResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RoleResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type UpdateRoleRequest struct {
	RoleId string `json:"role_id" url:"role_id"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateRoleRequest) GetRoleId() string {
	if u == nil {
		return ""
	}
	return u.RoleId
}

func (u *UpdateRoleRequest) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UpdateRoleRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateRoleRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateRoleRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateRoleRequest) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

type UploadFileError struct {
	Error string `json:"error" url:"error"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UploadFileError) GetError() string {
	if u == nil {
		return ""
	}
	return u.Error
}

func (u *UploadFileError) GetExtraProperties() map[string]interface{} {
	return u.extraProperties
}

func (u *UploadFileError) UnmarshalJSON(data []byte) error {
	type unmarshaler UploadFileError
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UploadFileError(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UploadFileError) String() string {
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}
