// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AcceptUserInviteArgs {
    pub invite_token: String,
}

impl From<AcceptUserInviteArgs> for super::Reducer {
    fn from(args: AcceptUserInviteArgs) -> Self {
        Self::AcceptUserInvite {
            invite_token: args.invite_token,
        }
    }
}

impl __sdk::InModule for AcceptUserInviteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `accept_user_invite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait accept_user_invite {
    /// Request that the remote module invoke the reducer `accept_user_invite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`accept_user_invite:accept_user_invite_then`] to run a callback after the reducer completes.
    fn accept_user_invite(&self, invite_token: String) -> __sdk::Result<()> {
        self.accept_user_invite_then(invite_token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `accept_user_invite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn accept_user_invite_then(
        &self,
        invite_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl accept_user_invite for super::RemoteReducers {
    fn accept_user_invite_then(
        &self,
        invite_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AcceptUserInviteArgs { invite_token }, callback)
    }
}
