// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct App {
    pub id: u64,
    pub uuid: String,
    pub name: String,
    pub org_id: String,
    pub description: String,
    pub enable_secrets: bool,
    pub is_managed_secret: bool,
    pub public_key: String,
    pub private_key: String,
    pub metadata: String,
    pub kms_key_version_id: String,
    pub encryption_migrated: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for App {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `App`.
///
/// Provides typed access to columns for query building.
pub struct AppCols {
    pub id: __sdk::__query_builder::Col<App, u64>,
    pub uuid: __sdk::__query_builder::Col<App, String>,
    pub name: __sdk::__query_builder::Col<App, String>,
    pub org_id: __sdk::__query_builder::Col<App, String>,
    pub description: __sdk::__query_builder::Col<App, String>,
    pub enable_secrets: __sdk::__query_builder::Col<App, bool>,
    pub is_managed_secret: __sdk::__query_builder::Col<App, bool>,
    pub public_key: __sdk::__query_builder::Col<App, String>,
    pub private_key: __sdk::__query_builder::Col<App, String>,
    pub metadata: __sdk::__query_builder::Col<App, String>,
    pub kms_key_version_id: __sdk::__query_builder::Col<App, String>,
    pub encryption_migrated: __sdk::__query_builder::Col<App, bool>,
    pub created_at: __sdk::__query_builder::Col<App, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<App, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for App {
    type Cols = AppCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AppCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            enable_secrets: __sdk::__query_builder::Col::new(table_name, "enable_secrets"),
            is_managed_secret: __sdk::__query_builder::Col::new(table_name, "is_managed_secret"),
            public_key: __sdk::__query_builder::Col::new(table_name, "public_key"),
            private_key: __sdk::__query_builder::Col::new(table_name, "private_key"),
            metadata: __sdk::__query_builder::Col::new(table_name, "metadata"),
            kms_key_version_id: __sdk::__query_builder::Col::new(table_name, "kms_key_version_id"),
            encryption_migrated: __sdk::__query_builder::Col::new(
                table_name,
                "encryption_migrated",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `App`.
///
/// Provides typed access to indexed columns for query building.
pub struct AppIxCols {
    pub id: __sdk::__query_builder::IxCol<App, u64>,
    pub org_id: __sdk::__query_builder::IxCol<App, String>,
}

impl __sdk::__query_builder::HasIxCols for App {
    type IxCols = AppIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AppIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for App {}
