// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AuthTuple {
    pub id: u64,
    pub subject: String,
    pub relation: String,
    pub object_type: String,
    pub object_id: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for AuthTuple {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AuthTuple`.
///
/// Provides typed access to columns for query building.
pub struct AuthTupleCols {
    pub id: __sdk::__query_builder::Col<AuthTuple, u64>,
    pub subject: __sdk::__query_builder::Col<AuthTuple, String>,
    pub relation: __sdk::__query_builder::Col<AuthTuple, String>,
    pub object_type: __sdk::__query_builder::Col<AuthTuple, String>,
    pub object_id: __sdk::__query_builder::Col<AuthTuple, String>,
    pub created_at: __sdk::__query_builder::Col<AuthTuple, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AuthTuple {
    type Cols = AuthTupleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AuthTupleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            subject: __sdk::__query_builder::Col::new(table_name, "subject"),
            relation: __sdk::__query_builder::Col::new(table_name, "relation"),
            object_type: __sdk::__query_builder::Col::new(table_name, "object_type"),
            object_id: __sdk::__query_builder::Col::new(table_name, "object_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AuthTuple`.
///
/// Provides typed access to indexed columns for query building.
pub struct AuthTupleIxCols {
    pub id: __sdk::__query_builder::IxCol<AuthTuple, u64>,
    pub object_id: __sdk::__query_builder::IxCol<AuthTuple, String>,
    pub object_type: __sdk::__query_builder::IxCol<AuthTuple, String>,
    pub subject: __sdk::__query_builder::IxCol<AuthTuple, String>,
}

impl __sdk::__query_builder::HasIxCols for AuthTuple {
    type IxCols = AuthTupleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AuthTupleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            object_id: __sdk::__query_builder::IxCol::new(table_name, "object_id"),
            object_type: __sdk::__query_builder::IxCol::new(table_name, "object_type"),
            subject: __sdk::__query_builder::IxCol::new(table_name, "subject"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AuthTuple {}
