// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BatchDecryptArgs {
    pub request_id: String,
    pub root_key_hex: String,
    pub org_id: String,
    pub scope_id: String,
    pub items_json: String,
}

impl From<BatchDecryptArgs> for super::Reducer {
    fn from(args: BatchDecryptArgs) -> Self {
        Self::BatchDecrypt {
            request_id: args.request_id,
            root_key_hex: args.root_key_hex,
            org_id: args.org_id,
            scope_id: args.scope_id,
            items_json: args.items_json,
        }
    }
}

impl __sdk::InModule for BatchDecryptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `batch_decrypt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait batch_decrypt {
    /// Request that the remote module invoke the reducer `batch_decrypt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`batch_decrypt:batch_decrypt_then`] to run a callback after the reducer completes.
    fn batch_decrypt(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        items_json: String,
    ) -> __sdk::Result<()> {
        self.batch_decrypt_then(
            request_id,
            root_key_hex,
            org_id,
            scope_id,
            items_json,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `batch_decrypt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn batch_decrypt_then(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        items_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl batch_decrypt for super::RemoteReducers {
    fn batch_decrypt_then(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        items_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BatchDecryptArgs {
                request_id,
                root_key_hex,
                org_id,
                scope_id,
                items_json,
            },
            callback,
        )
    }
}
