// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheckOcspArgs {
    pub request_id: String,
    pub serial_hex: String,
    pub org_id: String,
}

impl From<CheckOcspArgs> for super::Reducer {
    fn from(args: CheckOcspArgs) -> Self {
        Self::CheckOcsp {
            request_id: args.request_id,
            serial_hex: args.serial_hex,
            org_id: args.org_id,
        }
    }
}

impl __sdk::InModule for CheckOcspArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `check_ocsp`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait check_ocsp {
    /// Request that the remote module invoke the reducer `check_ocsp` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`check_ocsp:check_ocsp_then`] to run a callback after the reducer completes.
    fn check_ocsp(
        &self,
        request_id: String,
        serial_hex: String,
        org_id: String,
    ) -> __sdk::Result<()> {
        self.check_ocsp_then(request_id, serial_hex, org_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `check_ocsp` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn check_ocsp_then(
        &self,
        request_id: String,
        serial_hex: String,
        org_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl check_ocsp for super::RemoteReducers {
    fn check_ocsp_then(
        &self,
        request_id: String,
        serial_hex: String,
        org_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CheckOcspArgs {
                request_id,
                serial_hex,
                org_id,
            },
            callback,
        )
    }
}
