// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheckKeyExistsArgs {
    pub request_id: String,
    pub org_id: String,
    pub app_id: String,
    pub env_type_id: String,
    pub key: String,
    pub exclude_table: String,
}

impl From<CheckKeyExistsArgs> for super::Reducer {
    fn from(args: CheckKeyExistsArgs) -> Self {
        Self::CheckKeyExists {
            request_id: args.request_id,
            org_id: args.org_id,
            app_id: args.app_id,
            env_type_id: args.env_type_id,
            key: args.key,
            exclude_table: args.exclude_table,
        }
    }
}

impl __sdk::InModule for CheckKeyExistsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `check_key_exists`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait check_key_exists {
    /// Request that the remote module invoke the reducer `check_key_exists` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`check_key_exists:check_key_exists_then`] to run a callback after the reducer completes.
    fn check_key_exists(
        &self,
        request_id: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        exclude_table: String,
    ) -> __sdk::Result<()> {
        self.check_key_exists_then(
            request_id,
            org_id,
            app_id,
            env_type_id,
            key,
            exclude_table,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `check_key_exists` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn check_key_exists_then(
        &self,
        request_id: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        exclude_table: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl check_key_exists for super::RemoteReducers {
    fn check_key_exists_then(
        &self,
        request_id: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        exclude_table: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CheckKeyExistsArgs {
                request_id,
                org_id,
                app_id,
                env_type_id,
                key,
                exclude_table,
            },
            callback,
        )
    }
}
