// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CleanupOldResponsesArgs {
    pub older_than_micros: i64,
}

impl From<CleanupOldResponsesArgs> for super::Reducer {
    fn from(args: CleanupOldResponsesArgs) -> Self {
        Self::CleanupOldResponses {
            older_than_micros: args.older_than_micros,
        }
    }
}

impl __sdk::InModule for CleanupOldResponsesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cleanup_old_responses`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cleanup_old_responses {
    /// Request that the remote module invoke the reducer `cleanup_old_responses` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cleanup_old_responses:cleanup_old_responses_then`] to run a callback after the reducer completes.
    fn cleanup_old_responses(&self, older_than_micros: i64) -> __sdk::Result<()> {
        self.cleanup_old_responses_then(older_than_micros, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cleanup_old_responses` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cleanup_old_responses_then(
        &self,
        older_than_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cleanup_old_responses for super::RemoteReducers {
    fn cleanup_old_responses_then(
        &self,
        older_than_micros: i64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CleanupOldResponsesArgs { older_than_micros }, callback)
    }
}
