// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTeamWithAuthArgs {
    pub uuid: String,
    pub org_id: String,
    pub name: String,
    pub description: String,
    pub color: String,
}

impl From<CreateTeamWithAuthArgs> for super::Reducer {
    fn from(args: CreateTeamWithAuthArgs) -> Self {
        Self::CreateTeamWithAuth {
            uuid: args.uuid,
            org_id: args.org_id,
            name: args.name,
            description: args.description,
            color: args.color,
        }
    }
}

impl __sdk::InModule for CreateTeamWithAuthArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_team_with_auth`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_team_with_auth {
    /// Request that the remote module invoke the reducer `create_team_with_auth` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_team_with_auth:create_team_with_auth_then`] to run a callback after the reducer completes.
    fn create_team_with_auth(
        &self,
        uuid: String,
        org_id: String,
        name: String,
        description: String,
        color: String,
    ) -> __sdk::Result<()> {
        self.create_team_with_auth_then(uuid, org_id, name, description, color, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_team_with_auth` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_team_with_auth_then(
        &self,
        uuid: String,
        org_id: String,
        name: String,
        description: String,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_team_with_auth for super::RemoteReducers {
    fn create_team_with_auth_then(
        &self,
        uuid: String,
        org_id: String,
        name: String,
        description: String,
        color: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateTeamWithAuthArgs {
                uuid,
                org_id,
                name,
                description,
                color,
            },
            callback,
        )
    }
}
