// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateEnvArgs {
    pub root_key_hex: String,
    pub org_id: String,
    pub app_id: String,
    pub env_type_id: String,
    pub key: String,
    pub plaintext: String,
}

impl From<CreateEnvArgs> for super::Reducer {
    fn from(args: CreateEnvArgs) -> Self {
        Self::CreateEnv {
            root_key_hex: args.root_key_hex,
            org_id: args.org_id,
            app_id: args.app_id,
            env_type_id: args.env_type_id,
            key: args.key,
            plaintext: args.plaintext,
        }
    }
}

impl __sdk::InModule for CreateEnvArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_env`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_env {
    /// Request that the remote module invoke the reducer `create_env` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_env:create_env_then`] to run a callback after the reducer completes.
    fn create_env(
        &self,
        root_key_hex: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        plaintext: String,
    ) -> __sdk::Result<()> {
        self.create_env_then(
            root_key_hex,
            org_id,
            app_id,
            env_type_id,
            key,
            plaintext,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_env` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_env_then(
        &self,
        root_key_hex: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        plaintext: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_env for super::RemoteReducers {
    fn create_env_then(
        &self,
        root_key_hex: String,
        org_id: String,
        app_id: String,
        env_type_id: String,
        key: String,
        plaintext: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateEnvArgs {
                root_key_hex,
                org_id,
                app_id,
                env_type_id,
                key,
                plaintext,
            },
            callback,
        )
    }
}
