// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateUserInviteArgs {
    pub uuid: String,
    pub email: String,
    pub role_id: String,
    pub invite_token: String,
    pub org_id: String,
}

impl From<CreateUserInviteArgs> for super::Reducer {
    fn from(args: CreateUserInviteArgs) -> Self {
        Self::CreateUserInvite {
            uuid: args.uuid,
            email: args.email,
            role_id: args.role_id,
            invite_token: args.invite_token,
            org_id: args.org_id,
        }
    }
}

impl __sdk::InModule for CreateUserInviteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_user_invite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_user_invite {
    /// Request that the remote module invoke the reducer `create_user_invite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_user_invite:create_user_invite_then`] to run a callback after the reducer completes.
    fn create_user_invite(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        invite_token: String,
        org_id: String,
    ) -> __sdk::Result<()> {
        self.create_user_invite_then(uuid, email, role_id, invite_token, org_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_user_invite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_user_invite_then(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        invite_token: String,
        org_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_user_invite for super::RemoteReducers {
    fn create_user_invite_then(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        invite_token: String,
        org_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateUserInviteArgs {
                uuid,
                email,
                role_id,
                invite_token,
                org_id,
            },
            callback,
        )
    }
}
