// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateEnvPitArgs {
    pub uuid: String,
    pub org_id: String,
    pub env_type_id: String,
    pub user_id: String,
    pub app_id: String,
    pub change_request_message: String,
    pub changes: String,
}

impl From<CreateEnvPitArgs> for super::Reducer {
    fn from(args: CreateEnvPitArgs) -> Self {
        Self::CreateEnvPit {
            uuid: args.uuid,
            org_id: args.org_id,
            env_type_id: args.env_type_id,
            user_id: args.user_id,
            app_id: args.app_id,
            change_request_message: args.change_request_message,
            changes: args.changes,
        }
    }
}

impl __sdk::InModule for CreateEnvPitArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_env_pit`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_env_pit {
    /// Request that the remote module invoke the reducer `create_env_pit` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_env_pit:create_env_pit_then`] to run a callback after the reducer completes.
    fn create_env_pit(
        &self,
        uuid: String,
        org_id: String,
        env_type_id: String,
        user_id: String,
        app_id: String,
        change_request_message: String,
        changes: String,
    ) -> __sdk::Result<()> {
        self.create_env_pit_then(
            uuid,
            org_id,
            env_type_id,
            user_id,
            app_id,
            change_request_message,
            changes,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_env_pit` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_env_pit_then(
        &self,
        uuid: String,
        org_id: String,
        env_type_id: String,
        user_id: String,
        app_id: String,
        change_request_message: String,
        changes: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_env_pit for super::RemoteReducers {
    fn create_env_pit_then(
        &self,
        uuid: String,
        org_id: String,
        env_type_id: String,
        user_id: String,
        app_id: String,
        change_request_message: String,
        changes: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateEnvPitArgs {
                uuid,
                org_id,
                env_type_id,
                user_id,
                app_id,
                change_request_message,
                changes,
            },
            callback,
        )
    }
}
