// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateOrgInviteArgs {
    pub uuid: String,
    pub email: String,
    pub invite_token: String,
}

impl From<CreateOrgInviteArgs> for super::Reducer {
    fn from(args: CreateOrgInviteArgs) -> Self {
        Self::CreateOrgInvite {
            uuid: args.uuid,
            email: args.email,
            invite_token: args.invite_token,
        }
    }
}

impl __sdk::InModule for CreateOrgInviteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_org_invite`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_org_invite {
    /// Request that the remote module invoke the reducer `create_org_invite` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_org_invite:create_org_invite_then`] to run a callback after the reducer completes.
    fn create_org_invite(
        &self,
        uuid: String,
        email: String,
        invite_token: String,
    ) -> __sdk::Result<()> {
        self.create_org_invite_then(uuid, email, invite_token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_org_invite` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_org_invite_then(
        &self,
        uuid: String,
        email: String,
        invite_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_org_invite for super::RemoteReducers {
    fn create_org_invite_then(
        &self,
        uuid: String,
        email: String,
        invite_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateOrgInviteArgs {
                uuid,
                email,
                invite_token,
            },
            callback,
        )
    }
}
