// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCertRecordArgs {
    pub uuid: String,
    pub org_id: String,
    pub user_id: String,
    pub serial_hex: String,
    pub cert_type: String,
    pub subject_cn: String,
    pub subject_email: String,
    pub status: String,
    pub not_before: String,
    pub not_after: String,
    pub description: String,
    pub metadata: String,
}

impl From<CreateCertRecordArgs> for super::Reducer {
    fn from(args: CreateCertRecordArgs) -> Self {
        Self::CreateCertRecord {
            uuid: args.uuid,
            org_id: args.org_id,
            user_id: args.user_id,
            serial_hex: args.serial_hex,
            cert_type: args.cert_type,
            subject_cn: args.subject_cn,
            subject_email: args.subject_email,
            status: args.status,
            not_before: args.not_before,
            not_after: args.not_after,
            description: args.description,
            metadata: args.metadata,
        }
    }
}

impl __sdk::InModule for CreateCertRecordArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_cert_record`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_cert_record {
    /// Request that the remote module invoke the reducer `create_cert_record` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_cert_record:create_cert_record_then`] to run a callback after the reducer completes.
    fn create_cert_record(
        &self,
        uuid: String,
        org_id: String,
        user_id: String,
        serial_hex: String,
        cert_type: String,
        subject_cn: String,
        subject_email: String,
        status: String,
        not_before: String,
        not_after: String,
        description: String,
        metadata: String,
    ) -> __sdk::Result<()> {
        self.create_cert_record_then(
            uuid,
            org_id,
            user_id,
            serial_hex,
            cert_type,
            subject_cn,
            subject_email,
            status,
            not_before,
            not_after,
            description,
            metadata,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_cert_record` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_cert_record_then(
        &self,
        uuid: String,
        org_id: String,
        user_id: String,
        serial_hex: String,
        cert_type: String,
        subject_cn: String,
        subject_email: String,
        status: String,
        not_before: String,
        not_after: String,
        description: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_cert_record for super::RemoteReducers {
    fn create_cert_record_then(
        &self,
        uuid: String,
        org_id: String,
        user_id: String,
        serial_hex: String,
        cert_type: String,
        subject_cn: String,
        subject_email: String,
        status: String,
        not_before: String,
        not_after: String,
        description: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateCertRecordArgs {
                uuid,
                org_id,
                user_id,
                serial_hex,
                cert_type,
                subject_cn,
                subject_email,
                status,
                not_before,
                not_after,
                description,
                metadata,
            },
            callback,
        )
    }
}
