// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CrlEntry {
    pub id: u64,
    pub org_id: String,
    pub serial_hex: String,
    pub reason: u32,
    pub revoked_at: __sdk::Timestamp,
}

impl __sdk::InModule for CrlEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CrlEntry`.
///
/// Provides typed access to columns for query building.
pub struct CrlEntryCols {
    pub id: __sdk::__query_builder::Col<CrlEntry, u64>,
    pub org_id: __sdk::__query_builder::Col<CrlEntry, String>,
    pub serial_hex: __sdk::__query_builder::Col<CrlEntry, String>,
    pub reason: __sdk::__query_builder::Col<CrlEntry, u32>,
    pub revoked_at: __sdk::__query_builder::Col<CrlEntry, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CrlEntry {
    type Cols = CrlEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrlEntryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            serial_hex: __sdk::__query_builder::Col::new(table_name, "serial_hex"),
            reason: __sdk::__query_builder::Col::new(table_name, "reason"),
            revoked_at: __sdk::__query_builder::Col::new(table_name, "revoked_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CrlEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrlEntryIxCols {
    pub id: __sdk::__query_builder::IxCol<CrlEntry, u64>,
    pub org_id: __sdk::__query_builder::IxCol<CrlEntry, String>,
}

impl __sdk::__query_builder::HasIxCols for CrlEntry {
    type IxCols = CrlEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrlEntryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CrlEntry {}
