// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DecryptArgs {
    pub request_id: String,
    pub root_key_hex: String,
    pub org_id: String,
    pub scope_id: String,
    pub ciphertext: String,
    pub nonce: String,
    pub key_version: u32,
    pub aad: String,
}

impl From<DecryptArgs> for super::Reducer {
    fn from(args: DecryptArgs) -> Self {
        Self::Decrypt {
            request_id: args.request_id,
            root_key_hex: args.root_key_hex,
            org_id: args.org_id,
            scope_id: args.scope_id,
            ciphertext: args.ciphertext,
            nonce: args.nonce,
            key_version: args.key_version,
            aad: args.aad,
        }
    }
}

impl __sdk::InModule for DecryptArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `decrypt`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait decrypt {
    /// Request that the remote module invoke the reducer `decrypt` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`decrypt:decrypt_then`] to run a callback after the reducer completes.
    fn decrypt(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        ciphertext: String,
        nonce: String,
        key_version: u32,
        aad: String,
    ) -> __sdk::Result<()> {
        self.decrypt_then(
            request_id,
            root_key_hex,
            org_id,
            scope_id,
            ciphertext,
            nonce,
            key_version,
            aad,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `decrypt` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn decrypt_then(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        ciphertext: String,
        nonce: String,
        key_version: u32,
        aad: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl decrypt for super::RemoteReducers {
    fn decrypt_then(
        &self,
        request_id: String,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
        ciphertext: String,
        nonce: String,
        key_version: u32,
        aad: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            DecryptArgs {
                request_id,
                root_key_hex,
                org_id,
                scope_id,
                ciphertext,
                nonce,
                key_version,
                aad,
            },
            callback,
        )
    }
}
