// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::encrypted_gpg_type::EncryptedGpg;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `encrypted_gpg`.
///
/// Obtain a handle from the [`EncryptedGpgTableAccess::encrypted_gpg`] method on [`super::RemoteTables`],
/// like `ctx.db.encrypted_gpg()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encrypted_gpg().on_insert(...)`.
pub struct EncryptedGpgTableHandle<'ctx> {
    imp: __sdk::TableHandle<EncryptedGpg>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `encrypted_gpg`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EncryptedGpgTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EncryptedGpgTableHandle`], which mediates access to the table `encrypted_gpg`.
    fn encrypted_gpg(&self) -> EncryptedGpgTableHandle<'_>;
}

impl EncryptedGpgTableAccess for super::RemoteTables {
    fn encrypted_gpg(&self) -> EncryptedGpgTableHandle<'_> {
        EncryptedGpgTableHandle {
            imp: self.imp.get_table::<EncryptedGpg>("encrypted_gpg"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EncryptedGpgInsertCallbackId(__sdk::CallbackId);
pub struct EncryptedGpgDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EncryptedGpgTableHandle<'ctx> {
    type Row = EncryptedGpg;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EncryptedGpg> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EncryptedGpgInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncryptedGpgInsertCallbackId {
        EncryptedGpgInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EncryptedGpgInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EncryptedGpgDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncryptedGpgDeleteCallbackId {
        EncryptedGpgDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EncryptedGpgDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EncryptedGpgUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EncryptedGpgTableHandle<'ctx> {
    type UpdateCallbackId = EncryptedGpgUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EncryptedGpgUpdateCallbackId {
        EncryptedGpgUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EncryptedGpgUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `encrypted_gpg`,
/// which allows point queries on the field of the same name
/// via the [`EncryptedGpgIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encrypted_gpg().id().find(...)`.
pub struct EncryptedGpgIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EncryptedGpg, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EncryptedGpgTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `encrypted_gpg`.
    pub fn id(&self) -> EncryptedGpgIdUnique<'ctx> {
        EncryptedGpgIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EncryptedGpgIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EncryptedGpg> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EncryptedGpg>("encrypted_gpg");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EncryptedGpg>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EncryptedGpg>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EncryptedGpg`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait encrypted_gpgQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EncryptedGpg`.
    fn encrypted_gpg(&self) -> __sdk::__query_builder::Table<EncryptedGpg>;
}

impl encrypted_gpgQueryTableAccess for __sdk::QueryTableAccessor {
    fn encrypted_gpg(&self) -> __sdk::__query_builder::Table<EncryptedGpg> {
        __sdk::__query_builder::Table::new("encrypted_gpg")
    }
}
