// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::encrypted_secret_type::EncryptedSecret;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `encrypted_secret`.
///
/// Obtain a handle from the [`EncryptedSecretTableAccess::encrypted_secret`] method on [`super::RemoteTables`],
/// like `ctx.db.encrypted_secret()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encrypted_secret().on_insert(...)`.
pub struct EncryptedSecretTableHandle<'ctx> {
    imp: __sdk::TableHandle<EncryptedSecret>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `encrypted_secret`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EncryptedSecretTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EncryptedSecretTableHandle`], which mediates access to the table `encrypted_secret`.
    fn encrypted_secret(&self) -> EncryptedSecretTableHandle<'_>;
}

impl EncryptedSecretTableAccess for super::RemoteTables {
    fn encrypted_secret(&self) -> EncryptedSecretTableHandle<'_> {
        EncryptedSecretTableHandle {
            imp: self.imp.get_table::<EncryptedSecret>("encrypted_secret"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EncryptedSecretInsertCallbackId(__sdk::CallbackId);
pub struct EncryptedSecretDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EncryptedSecretTableHandle<'ctx> {
    type Row = EncryptedSecret;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EncryptedSecret> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EncryptedSecretInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncryptedSecretInsertCallbackId {
        EncryptedSecretInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EncryptedSecretInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EncryptedSecretDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EncryptedSecretDeleteCallbackId {
        EncryptedSecretDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EncryptedSecretDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EncryptedSecretUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EncryptedSecretTableHandle<'ctx> {
    type UpdateCallbackId = EncryptedSecretUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EncryptedSecretUpdateCallbackId {
        EncryptedSecretUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EncryptedSecretUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `encrypted_secret`,
/// which allows point queries on the field of the same name
/// via the [`EncryptedSecretIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.encrypted_secret().id().find(...)`.
pub struct EncryptedSecretIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EncryptedSecret, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EncryptedSecretTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `encrypted_secret`.
    pub fn id(&self) -> EncryptedSecretIdUnique<'ctx> {
        EncryptedSecretIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EncryptedSecretIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EncryptedSecret> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EncryptedSecret>("encrypted_secret");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EncryptedSecret>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EncryptedSecret>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EncryptedSecret`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait encrypted_secretQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EncryptedSecret`.
    fn encrypted_secret(&self) -> __sdk::__query_builder::Table<EncryptedSecret>;
}

impl encrypted_secretQueryTableAccess for __sdk::QueryTableAccessor {
    fn encrypted_secret(&self) -> __sdk::__query_builder::Table<EncryptedSecret> {
        __sdk::__query_builder::Table::new("encrypted_secret")
    }
}
