// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetApiKeyByKeyArgs {
    pub request_id: String,
    pub key: String,
}

impl From<GetApiKeyByKeyArgs> for super::Reducer {
    fn from(args: GetApiKeyByKeyArgs) -> Self {
        Self::GetApiKeyByKey {
            request_id: args.request_id,
            key: args.key,
        }
    }
}

impl __sdk::InModule for GetApiKeyByKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_api_key_by_key`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_api_key_by_key {
    /// Request that the remote module invoke the reducer `get_api_key_by_key` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_api_key_by_key:get_api_key_by_key_then`] to run a callback after the reducer completes.
    fn get_api_key_by_key(&self, request_id: String, key: String) -> __sdk::Result<()> {
        self.get_api_key_by_key_then(request_id, key, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_api_key_by_key` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_api_key_by_key_then(
        &self,
        request_id: String,
        key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_api_key_by_key for super::RemoteReducers {
    fn get_api_key_by_key_then(
        &self,
        request_id: String,
        key: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetApiKeyByKeyArgs { request_id, key }, callback)
    }
}
