// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetCrlArgs {
    pub request_id: String,
    pub org_id: String,
    pub delta_only: bool,
}

impl From<GetCrlArgs> for super::Reducer {
    fn from(args: GetCrlArgs) -> Self {
        Self::GetCrl {
            request_id: args.request_id,
            org_id: args.org_id,
            delta_only: args.delta_only,
        }
    }
}

impl __sdk::InModule for GetCrlArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_crl`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_crl {
    /// Request that the remote module invoke the reducer `get_crl` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_crl:get_crl_then`] to run a callback after the reducer completes.
    fn get_crl(&self, request_id: String, org_id: String, delta_only: bool) -> __sdk::Result<()> {
        self.get_crl_then(request_id, org_id, delta_only, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_crl` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_crl_then(
        &self,
        request_id: String,
        org_id: String,
        delta_only: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_crl for super::RemoteReducers {
    fn get_crl_then(
        &self,
        request_id: String,
        org_id: String,
        delta_only: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            GetCrlArgs {
                request_id,
                org_id,
                delta_only,
            },
            callback,
        )
    }
}
