// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetOrgBySlugArgs {
    pub request_id: String,
    pub slug: String,
}

impl From<GetOrgBySlugArgs> for super::Reducer {
    fn from(args: GetOrgBySlugArgs) -> Self {
        Self::GetOrgBySlug {
            request_id: args.request_id,
            slug: args.slug,
        }
    }
}

impl __sdk::InModule for GetOrgBySlugArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_org_by_slug`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_org_by_slug {
    /// Request that the remote module invoke the reducer `get_org_by_slug` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_org_by_slug:get_org_by_slug_then`] to run a callback after the reducer completes.
    fn get_org_by_slug(&self, request_id: String, slug: String) -> __sdk::Result<()> {
        self.get_org_by_slug_then(request_id, slug, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_org_by_slug` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_org_by_slug_then(
        &self,
        request_id: String,
        slug: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_org_by_slug for super::RemoteReducers {
    fn get_org_by_slug_then(
        &self,
        request_id: String,
        slug: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetOrgBySlugArgs { request_id, slug }, callback)
    }
}
