// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gpg_key_meta_type::GpgKeyMeta;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `gpg_key_meta`.
///
/// Obtain a handle from the [`GpgKeyMetaTableAccess::gpg_key_meta`] method on [`super::RemoteTables`],
/// like `ctx.db.gpg_key_meta()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gpg_key_meta().on_insert(...)`.
pub struct GpgKeyMetaTableHandle<'ctx> {
    imp: __sdk::TableHandle<GpgKeyMeta>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `gpg_key_meta`.
///
/// Implemented for [`super::RemoteTables`].
pub trait GpgKeyMetaTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`GpgKeyMetaTableHandle`], which mediates access to the table `gpg_key_meta`.
    fn gpg_key_meta(&self) -> GpgKeyMetaTableHandle<'_>;
}

impl GpgKeyMetaTableAccess for super::RemoteTables {
    fn gpg_key_meta(&self) -> GpgKeyMetaTableHandle<'_> {
        GpgKeyMetaTableHandle {
            imp: self.imp.get_table::<GpgKeyMeta>("gpg_key_meta"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct GpgKeyMetaInsertCallbackId(__sdk::CallbackId);
pub struct GpgKeyMetaDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for GpgKeyMetaTableHandle<'ctx> {
    type Row = GpgKeyMeta;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GpgKeyMeta> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = GpgKeyMetaInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GpgKeyMetaInsertCallbackId {
        GpgKeyMetaInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: GpgKeyMetaInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = GpgKeyMetaDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> GpgKeyMetaDeleteCallbackId {
        GpgKeyMetaDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: GpgKeyMetaDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct GpgKeyMetaUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for GpgKeyMetaTableHandle<'ctx> {
    type UpdateCallbackId = GpgKeyMetaUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> GpgKeyMetaUpdateCallbackId {
        GpgKeyMetaUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: GpgKeyMetaUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `gpg_key_meta`,
/// which allows point queries on the field of the same name
/// via the [`GpgKeyMetaIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gpg_key_meta().id().find(...)`.
pub struct GpgKeyMetaIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GpgKeyMeta, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GpgKeyMetaTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `gpg_key_meta`.
    pub fn id(&self) -> GpgKeyMetaIdUnique<'ctx> {
        GpgKeyMetaIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GpgKeyMetaIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<GpgKeyMeta> {
        self.imp.find(col_val)
    }
}

/// Access to the `fingerprint` unique index on the table `gpg_key_meta`,
/// which allows point queries on the field of the same name
/// via the [`GpgKeyMetaFingerprintUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.gpg_key_meta().fingerprint().find(...)`.
pub struct GpgKeyMetaFingerprintUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GpgKeyMeta, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> GpgKeyMetaTableHandle<'ctx> {
    /// Get a handle on the `fingerprint` unique index on the table `gpg_key_meta`.
    pub fn fingerprint(&self) -> GpgKeyMetaFingerprintUnique<'ctx> {
        GpgKeyMetaFingerprintUnique {
            imp: self.imp.get_unique_constraint::<String>("fingerprint"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> GpgKeyMetaFingerprintUnique<'ctx> {
    /// Find the subscribed row whose `fingerprint` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<GpgKeyMeta> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GpgKeyMeta>("gpg_key_meta");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("fingerprint", |row| &row.fingerprint);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<GpgKeyMeta>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GpgKeyMeta>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GpgKeyMeta`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait gpg_key_metaQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GpgKeyMeta`.
    fn gpg_key_meta(&self) -> __sdk::__query_builder::Table<GpgKeyMeta>;
}

impl gpg_key_metaQueryTableAccess for __sdk::QueryTableAccessor {
    fn gpg_key_meta(&self) -> __sdk::__query_builder::Table<GpgKeyMeta> {
        __sdk::__query_builder::Table::new("gpg_key_meta")
    }
}
