// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InviteUser {
    pub id: u64,
    pub uuid: String,
    pub email: String,
    pub role_id: String,
    pub invite_token: String,
    pub is_accepted: bool,
    pub org_id: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for InviteUser {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InviteUser`.
///
/// Provides typed access to columns for query building.
pub struct InviteUserCols {
    pub id: __sdk::__query_builder::Col<InviteUser, u64>,
    pub uuid: __sdk::__query_builder::Col<InviteUser, String>,
    pub email: __sdk::__query_builder::Col<InviteUser, String>,
    pub role_id: __sdk::__query_builder::Col<InviteUser, String>,
    pub invite_token: __sdk::__query_builder::Col<InviteUser, String>,
    pub is_accepted: __sdk::__query_builder::Col<InviteUser, bool>,
    pub org_id: __sdk::__query_builder::Col<InviteUser, String>,
    pub created_at: __sdk::__query_builder::Col<InviteUser, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<InviteUser, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for InviteUser {
    type Cols = InviteUserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InviteUserCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            invite_token: __sdk::__query_builder::Col::new(table_name, "invite_token"),
            is_accepted: __sdk::__query_builder::Col::new(table_name, "is_accepted"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InviteUser`.
///
/// Provides typed access to indexed columns for query building.
pub struct InviteUserIxCols {
    pub email: __sdk::__query_builder::IxCol<InviteUser, String>,
    pub id: __sdk::__query_builder::IxCol<InviteUser, u64>,
    pub org_id: __sdk::__query_builder::IxCol<InviteUser, String>,
}

impl __sdk::__query_builder::HasIxCols for InviteUser {
    type IxCols = InviteUserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InviteUserIxCols {
            email: __sdk::__query_builder::IxCol::new(table_name, "email"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InviteUser {}
