// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::invite_user_type::InviteUser;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `invite_user`.
///
/// Obtain a handle from the [`InviteUserTableAccess::invite_user`] method on [`super::RemoteTables`],
/// like `ctx.db.invite_user()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.invite_user().on_insert(...)`.
pub struct InviteUserTableHandle<'ctx> {
    imp: __sdk::TableHandle<InviteUser>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `invite_user`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InviteUserTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InviteUserTableHandle`], which mediates access to the table `invite_user`.
    fn invite_user(&self) -> InviteUserTableHandle<'_>;
}

impl InviteUserTableAccess for super::RemoteTables {
    fn invite_user(&self) -> InviteUserTableHandle<'_> {
        InviteUserTableHandle {
            imp: self.imp.get_table::<InviteUser>("invite_user"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InviteUserInsertCallbackId(__sdk::CallbackId);
pub struct InviteUserDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InviteUserTableHandle<'ctx> {
    type Row = InviteUser;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InviteUser> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InviteUserInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InviteUserInsertCallbackId {
        InviteUserInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InviteUserInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InviteUserDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InviteUserDeleteCallbackId {
        InviteUserDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InviteUserDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct InviteUserUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InviteUserTableHandle<'ctx> {
    type UpdateCallbackId = InviteUserUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InviteUserUpdateCallbackId {
        InviteUserUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InviteUserUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `invite_user`,
/// which allows point queries on the field of the same name
/// via the [`InviteUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.invite_user().id().find(...)`.
pub struct InviteUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InviteUser, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InviteUserTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `invite_user`.
    pub fn id(&self) -> InviteUserIdUnique<'ctx> {
        InviteUserIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InviteUserIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InviteUser> {
        self.imp.find(col_val)
    }
}

/// Access to the `email` unique index on the table `invite_user`,
/// which allows point queries on the field of the same name
/// via the [`InviteUserEmailUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.invite_user().email().find(...)`.
pub struct InviteUserEmailUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InviteUser, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InviteUserTableHandle<'ctx> {
    /// Get a handle on the `email` unique index on the table `invite_user`.
    pub fn email(&self) -> InviteUserEmailUnique<'ctx> {
        InviteUserEmailUnique {
            imp: self.imp.get_unique_constraint::<String>("email"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InviteUserEmailUnique<'ctx> {
    /// Find the subscribed row whose `email` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<InviteUser> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InviteUser>("invite_user");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("email", |row| &row.email);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InviteUser>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InviteUser>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InviteUser`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait invite_userQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InviteUser`.
    fn invite_user(&self) -> __sdk::__query_builder::Table<InviteUser>;
}

impl invite_userQueryTableAccess for __sdk::QueryTableAccessor {
    fn invite_user(&self) -> __sdk::__query_builder::Table<InviteUser> {
        __sdk::__query_builder::Table::new("invite_user")
    }
}
