// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InviteOrg {
    pub id: u64,
    pub uuid: String,
    pub email: String,
    pub invite_token: String,
    pub is_accepted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for InviteOrg {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InviteOrg`.
///
/// Provides typed access to columns for query building.
pub struct InviteOrgCols {
    pub id: __sdk::__query_builder::Col<InviteOrg, u64>,
    pub uuid: __sdk::__query_builder::Col<InviteOrg, String>,
    pub email: __sdk::__query_builder::Col<InviteOrg, String>,
    pub invite_token: __sdk::__query_builder::Col<InviteOrg, String>,
    pub is_accepted: __sdk::__query_builder::Col<InviteOrg, bool>,
    pub created_at: __sdk::__query_builder::Col<InviteOrg, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<InviteOrg, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for InviteOrg {
    type Cols = InviteOrgCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InviteOrgCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            invite_token: __sdk::__query_builder::Col::new(table_name, "invite_token"),
            is_accepted: __sdk::__query_builder::Col::new(table_name, "is_accepted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InviteOrg`.
///
/// Provides typed access to indexed columns for query building.
pub struct InviteOrgIxCols {
    pub id: __sdk::__query_builder::IxCol<InviteOrg, u64>,
    pub invite_token: __sdk::__query_builder::IxCol<InviteOrg, String>,
}

impl __sdk::__query_builder::HasIxCols for InviteOrg {
    type IxCols = InviteOrgIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InviteOrgIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            invite_token: __sdk::__query_builder::IxCol::new(table_name, "invite_token"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InviteOrg {}
