// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IssueMemberCertArgs {
    pub request_id: String,
    pub root_key_hex: String,
    pub user_id: String,
    pub member_email: String,
    pub org_id: String,
    pub role: String,
}

impl From<IssueMemberCertArgs> for super::Reducer {
    fn from(args: IssueMemberCertArgs) -> Self {
        Self::IssueMemberCert {
            request_id: args.request_id,
            root_key_hex: args.root_key_hex,
            user_id: args.user_id,
            member_email: args.member_email,
            org_id: args.org_id,
            role: args.role,
        }
    }
}

impl __sdk::InModule for IssueMemberCertArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `issue_member_cert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait issue_member_cert {
    /// Request that the remote module invoke the reducer `issue_member_cert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`issue_member_cert:issue_member_cert_then`] to run a callback after the reducer completes.
    fn issue_member_cert(
        &self,
        request_id: String,
        root_key_hex: String,
        user_id: String,
        member_email: String,
        org_id: String,
        role: String,
    ) -> __sdk::Result<()> {
        self.issue_member_cert_then(
            request_id,
            root_key_hex,
            user_id,
            member_email,
            org_id,
            role,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `issue_member_cert` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn issue_member_cert_then(
        &self,
        request_id: String,
        root_key_hex: String,
        user_id: String,
        member_email: String,
        org_id: String,
        role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl issue_member_cert for super::RemoteReducers {
    fn issue_member_cert_then(
        &self,
        request_id: String,
        root_key_hex: String,
        user_id: String,
        member_email: String,
        org_id: String,
        role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IssueMemberCertArgs {
                request_id,
                root_key_hex,
                user_id,
                member_email,
                org_id,
                role,
            },
            callback,
        )
    }
}
