// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::org_type::Org;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `org`.
///
/// Obtain a handle from the [`OrgTableAccess::org`] method on [`super::RemoteTables`],
/// like `ctx.db.org()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.org().on_insert(...)`.
pub struct OrgTableHandle<'ctx> {
    imp: __sdk::TableHandle<Org>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `org`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OrgTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OrgTableHandle`], which mediates access to the table `org`.
    fn org(&self) -> OrgTableHandle<'_>;
}

impl OrgTableAccess for super::RemoteTables {
    fn org(&self) -> OrgTableHandle<'_> {
        OrgTableHandle {
            imp: self.imp.get_table::<Org>("org"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OrgInsertCallbackId(__sdk::CallbackId);
pub struct OrgDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for OrgTableHandle<'ctx> {
    type Row = Org;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Org> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OrgInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OrgInsertCallbackId {
        OrgInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OrgInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OrgDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OrgDeleteCallbackId {
        OrgDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OrgDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct OrgUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for OrgTableHandle<'ctx> {
    type UpdateCallbackId = OrgUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> OrgUpdateCallbackId {
        OrgUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: OrgUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `org`,
/// which allows point queries on the field of the same name
/// via the [`OrgIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.org().id().find(...)`.
pub struct OrgIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Org, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OrgTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `org`.
    pub fn id(&self) -> OrgIdUnique<'ctx> {
        OrgIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OrgIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Org> {
        self.imp.find(col_val)
    }
}

/// Access to the `slug` unique index on the table `org`,
/// which allows point queries on the field of the same name
/// via the [`OrgSlugUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.org().slug().find(...)`.
pub struct OrgSlugUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Org, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> OrgTableHandle<'ctx> {
    /// Get a handle on the `slug` unique index on the table `org`.
    pub fn slug(&self) -> OrgSlugUnique<'ctx> {
        OrgSlugUnique {
            imp: self.imp.get_unique_constraint::<String>("slug"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> OrgSlugUnique<'ctx> {
    /// Find the subscribed row whose `slug` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Org> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Org>("org");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("slug", |row| &row.slug);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Org>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Org>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Org`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait orgQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Org`.
    fn org(&self) -> __sdk::__query_builder::Table<Org>;
}

impl orgQueryTableAccess for __sdk::QueryTableAccessor {
    fn org(&self) -> __sdk::__query_builder::Table<Org> {
        __sdk::__query_builder::Table::new("org")
    }
}
