// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pki_certificate_type::PkiCertificate;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pki_certificate`.
///
/// Obtain a handle from the [`PkiCertificateTableAccess::pki_certificate`] method on [`super::RemoteTables`],
/// like `ctx.db.pki_certificate()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pki_certificate().on_insert(...)`.
pub struct PkiCertificateTableHandle<'ctx> {
    imp: __sdk::TableHandle<PkiCertificate>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pki_certificate`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PkiCertificateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PkiCertificateTableHandle`], which mediates access to the table `pki_certificate`.
    fn pki_certificate(&self) -> PkiCertificateTableHandle<'_>;
}

impl PkiCertificateTableAccess for super::RemoteTables {
    fn pki_certificate(&self) -> PkiCertificateTableHandle<'_> {
        PkiCertificateTableHandle {
            imp: self.imp.get_table::<PkiCertificate>("pki_certificate"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PkiCertificateInsertCallbackId(__sdk::CallbackId);
pub struct PkiCertificateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PkiCertificateTableHandle<'ctx> {
    type Row = PkiCertificate;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PkiCertificate> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PkiCertificateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PkiCertificateInsertCallbackId {
        PkiCertificateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PkiCertificateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PkiCertificateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PkiCertificateDeleteCallbackId {
        PkiCertificateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PkiCertificateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PkiCertificateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PkiCertificateTableHandle<'ctx> {
    type UpdateCallbackId = PkiCertificateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PkiCertificateUpdateCallbackId {
        PkiCertificateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PkiCertificateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `pki_certificate`,
/// which allows point queries on the field of the same name
/// via the [`PkiCertificateIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pki_certificate().id().find(...)`.
pub struct PkiCertificateIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PkiCertificate, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PkiCertificateTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `pki_certificate`.
    pub fn id(&self) -> PkiCertificateIdUnique<'ctx> {
        PkiCertificateIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PkiCertificateIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PkiCertificate> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PkiCertificate>("pki_certificate");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PkiCertificate>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PkiCertificate>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PkiCertificate`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait pki_certificateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PkiCertificate`.
    fn pki_certificate(&self) -> __sdk::__query_builder::Table<PkiCertificate>;
}

impl pki_certificateQueryTableAccess for __sdk::QueryTableAccessor {
    fn pki_certificate(&self) -> __sdk::__query_builder::Table<PkiCertificate> {
        __sdk::__query_builder::Table::new("pki_certificate")
    }
}
