// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ReadTuplesArgs {
    pub request_id: String,
    pub subject: String,
    pub relation: String,
    pub object_type: String,
    pub object_id: String,
}

impl From<ReadTuplesArgs> for super::Reducer {
    fn from(args: ReadTuplesArgs) -> Self {
        Self::ReadTuples {
            request_id: args.request_id,
            subject: args.subject,
            relation: args.relation,
            object_type: args.object_type,
            object_id: args.object_id,
        }
    }
}

impl __sdk::InModule for ReadTuplesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `read_tuples`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait read_tuples {
    /// Request that the remote module invoke the reducer `read_tuples` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`read_tuples:read_tuples_then`] to run a callback after the reducer completes.
    fn read_tuples(
        &self,
        request_id: String,
        subject: String,
        relation: String,
        object_type: String,
        object_id: String,
    ) -> __sdk::Result<()> {
        self.read_tuples_then(
            request_id,
            subject,
            relation,
            object_type,
            object_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `read_tuples` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn read_tuples_then(
        &self,
        request_id: String,
        subject: String,
        relation: String,
        object_type: String,
        object_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl read_tuples for super::RemoteReducers {
    fn read_tuples_then(
        &self,
        request_id: String,
        subject: String,
        relation: String,
        object_type: String,
        object_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ReadTuplesArgs {
                request_id,
                subject,
                relation,
                object_type,
                object_id,
            },
            callback,
        )
    }
}
