// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ReducerResponse {
    pub id: u64,
    pub request_id: String,
    pub data: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for ReducerResponse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ReducerResponse`.
///
/// Provides typed access to columns for query building.
pub struct ReducerResponseCols {
    pub id: __sdk::__query_builder::Col<ReducerResponse, u64>,
    pub request_id: __sdk::__query_builder::Col<ReducerResponse, String>,
    pub data: __sdk::__query_builder::Col<ReducerResponse, String>,
    pub created_at: __sdk::__query_builder::Col<ReducerResponse, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ReducerResponse {
    type Cols = ReducerResponseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReducerResponseCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ReducerResponse`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReducerResponseIxCols {
    pub id: __sdk::__query_builder::IxCol<ReducerResponse, u64>,
    pub request_id: __sdk::__query_builder::IxCol<ReducerResponse, String>,
}

impl __sdk::__query_builder::HasIxCols for ReducerResponse {
    type IxCols = ReducerResponseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReducerResponseIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            request_id: __sdk::__query_builder::IxCol::new(table_name, "request_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ReducerResponse {}
