// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RotateDataKeyArgs {
    pub root_key_hex: String,
    pub org_id: String,
    pub scope_id: String,
}

impl From<RotateDataKeyArgs> for super::Reducer {
    fn from(args: RotateDataKeyArgs) -> Self {
        Self::RotateDataKey {
            root_key_hex: args.root_key_hex,
            org_id: args.org_id,
            scope_id: args.scope_id,
        }
    }
}

impl __sdk::InModule for RotateDataKeyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rotate_data_key`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rotate_data_key {
    /// Request that the remote module invoke the reducer `rotate_data_key` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rotate_data_key:rotate_data_key_then`] to run a callback after the reducer completes.
    fn rotate_data_key(
        &self,
        root_key_hex: String,
        org_id: String,
        scope_id: String,
    ) -> __sdk::Result<()> {
        self.rotate_data_key_then(root_key_hex, org_id, scope_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rotate_data_key` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rotate_data_key_then(
        &self,
        root_key_hex: String,
        org_id: String,
        scope_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl rotate_data_key for super::RemoteReducers {
    fn rotate_data_key_then(
        &self,
        root_key_hex: String,
        org_id: String,
        scope_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RotateDataKeyArgs {
                root_key_hex,
                org_id,
                scope_id,
            },
            callback,
        )
    }
}
