// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SecretStorePit {
    pub id: u64,
    pub uuid: String,
    pub org_id: String,
    pub env_type_id: String,
    pub user_id: String,
    pub app_id: String,
    pub change_request_message: String,
    pub changes: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SecretStorePit {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SecretStorePit`.
///
/// Provides typed access to columns for query building.
pub struct SecretStorePitCols {
    pub id: __sdk::__query_builder::Col<SecretStorePit, u64>,
    pub uuid: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub org_id: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub env_type_id: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub user_id: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub app_id: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub change_request_message: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub changes: __sdk::__query_builder::Col<SecretStorePit, String>,
    pub created_at: __sdk::__query_builder::Col<SecretStorePit, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SecretStorePit, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SecretStorePit {
    type Cols = SecretStorePitCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SecretStorePitCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            env_type_id: __sdk::__query_builder::Col::new(table_name, "env_type_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            app_id: __sdk::__query_builder::Col::new(table_name, "app_id"),
            change_request_message: __sdk::__query_builder::Col::new(
                table_name,
                "change_request_message",
            ),
            changes: __sdk::__query_builder::Col::new(table_name, "changes"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SecretStorePit`.
///
/// Provides typed access to indexed columns for query building.
pub struct SecretStorePitIxCols {
    pub id: __sdk::__query_builder::IxCol<SecretStorePit, u64>,
    pub org_id: __sdk::__query_builder::IxCol<SecretStorePit, String>,
}

impl __sdk::__query_builder::HasIxCols for SecretStorePit {
    type IxCols = SecretStorePitIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SecretStorePitIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SecretStorePit {}
