// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Sequence {
    pub name: String,
    pub value: u64,
}

impl __sdk::InModule for Sequence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Sequence`.
///
/// Provides typed access to columns for query building.
pub struct SequenceCols {
    pub name: __sdk::__query_builder::Col<Sequence, String>,
    pub value: __sdk::__query_builder::Col<Sequence, u64>,
}

impl __sdk::__query_builder::HasCols for Sequence {
    type Cols = SequenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SequenceCols {
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            value: __sdk::__query_builder::Col::new(table_name, "value"),
        }
    }
}

/// Indexed column accessor struct for the table `Sequence`.
///
/// Provides typed access to indexed columns for query building.
pub struct SequenceIxCols {
    pub name: __sdk::__query_builder::IxCol<Sequence, String>,
}

impl __sdk::__query_builder::HasIxCols for Sequence {
    type IxCols = SequenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SequenceIxCols {
            name: __sdk::__query_builder::IxCol::new(table_name, "name"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Sequence {}
