// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::team_type::Team;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `team`.
///
/// Obtain a handle from the [`TeamTableAccess::team`] method on [`super::RemoteTables`],
/// like `ctx.db.team()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.team().on_insert(...)`.
pub struct TeamTableHandle<'ctx> {
    imp: __sdk::TableHandle<Team>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `team`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TeamTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TeamTableHandle`], which mediates access to the table `team`.
    fn team(&self) -> TeamTableHandle<'_>;
}

impl TeamTableAccess for super::RemoteTables {
    fn team(&self) -> TeamTableHandle<'_> {
        TeamTableHandle {
            imp: self.imp.get_table::<Team>("team"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TeamInsertCallbackId(__sdk::CallbackId);
pub struct TeamDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TeamTableHandle<'ctx> {
    type Row = Team;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Team> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TeamInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TeamInsertCallbackId {
        TeamInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TeamInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TeamDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TeamDeleteCallbackId {
        TeamDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TeamDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct TeamUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TeamTableHandle<'ctx> {
    type UpdateCallbackId = TeamUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TeamUpdateCallbackId {
        TeamUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TeamUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `team`,
/// which allows point queries on the field of the same name
/// via the [`TeamIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.team().id().find(...)`.
pub struct TeamIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Team, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TeamTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `team`.
    pub fn id(&self) -> TeamIdUnique<'ctx> {
        TeamIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TeamIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Team> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Team>("team");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Team>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Team>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Team`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait teamQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Team`.
    fn team(&self) -> __sdk::__query_builder::Table<Team>;
}

impl teamQueryTableAccess for __sdk::QueryTableAccessor {
    fn team(&self) -> __sdk::__query_builder::Table<Team> {
        __sdk::__query_builder::Table::new("team")
    }
}
