// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TeamMember {
    pub id: u64,
    pub uuid: String,
    pub team_id: String,
    pub user_id: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for TeamMember {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TeamMember`.
///
/// Provides typed access to columns for query building.
pub struct TeamMemberCols {
    pub id: __sdk::__query_builder::Col<TeamMember, u64>,
    pub uuid: __sdk::__query_builder::Col<TeamMember, String>,
    pub team_id: __sdk::__query_builder::Col<TeamMember, String>,
    pub user_id: __sdk::__query_builder::Col<TeamMember, String>,
    pub created_at: __sdk::__query_builder::Col<TeamMember, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for TeamMember {
    type Cols = TeamMemberCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TeamMemberCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            team_id: __sdk::__query_builder::Col::new(table_name, "team_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TeamMember`.
///
/// Provides typed access to indexed columns for query building.
pub struct TeamMemberIxCols {
    pub id: __sdk::__query_builder::IxCol<TeamMember, u64>,
    pub team_id: __sdk::__query_builder::IxCol<TeamMember, String>,
    pub user_id: __sdk::__query_builder::IxCol<TeamMember, String>,
}

impl __sdk::__query_builder::HasIxCols for TeamMember {
    type IxCols = TeamMemberIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TeamMemberIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            team_id: __sdk::__query_builder::IxCol::new(table_name, "team_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TeamMember {}
