// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateWebhookArgs {
    pub uuid: String,
    pub name: String,
    pub url: String,
    pub event_types: String,
    pub is_active: bool,
}

impl From<UpdateWebhookArgs> for super::Reducer {
    fn from(args: UpdateWebhookArgs) -> Self {
        Self::UpdateWebhook {
            uuid: args.uuid,
            name: args.name,
            url: args.url,
            event_types: args.event_types,
            is_active: args.is_active,
        }
    }
}

impl __sdk::InModule for UpdateWebhookArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_webhook`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_webhook {
    /// Request that the remote module invoke the reducer `update_webhook` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_webhook:update_webhook_then`] to run a callback after the reducer completes.
    fn update_webhook(
        &self,
        uuid: String,
        name: String,
        url: String,
        event_types: String,
        is_active: bool,
    ) -> __sdk::Result<()> {
        self.update_webhook_then(uuid, name, url, event_types, is_active, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_webhook` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_webhook_then(
        &self,
        uuid: String,
        name: String,
        url: String,
        event_types: String,
        is_active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_webhook for super::RemoteReducers {
    fn update_webhook_then(
        &self,
        uuid: String,
        name: String,
        url: String,
        event_types: String,
        is_active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateWebhookArgs {
                uuid,
                name,
                url,
                event_types,
                is_active,
            },
            callback,
        )
    }
}
