// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateUserArgs {
    pub uuid: String,
    pub email: String,
    pub role_id: String,
    pub full_name: String,
    pub profile_picture_url: String,
    pub is_active: bool,
}

impl From<UpdateUserArgs> for super::Reducer {
    fn from(args: UpdateUserArgs) -> Self {
        Self::UpdateUser {
            uuid: args.uuid,
            email: args.email,
            role_id: args.role_id,
            full_name: args.full_name,
            profile_picture_url: args.profile_picture_url,
            is_active: args.is_active,
        }
    }
}

impl __sdk::InModule for UpdateUserArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_user {
    /// Request that the remote module invoke the reducer `update_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_user:update_user_then`] to run a callback after the reducer completes.
    fn update_user(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        full_name: String,
        profile_picture_url: String,
        is_active: bool,
    ) -> __sdk::Result<()> {
        self.update_user_then(
            uuid,
            email,
            role_id,
            full_name,
            profile_picture_url,
            is_active,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_user` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_user_then(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        full_name: String,
        profile_picture_url: String,
        is_active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_user for super::RemoteReducers {
    fn update_user_then(
        &self,
        uuid: String,
        email: String,
        role_id: String,
        full_name: String,
        profile_picture_url: String,
        is_active: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateUserArgs {
                uuid,
                email,
                role_id,
                full_name,
                profile_picture_url,
                is_active,
            },
            callback,
        )
    }
}
