// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateAppArgs {
    pub uuid: String,
    pub name: String,
    pub description: String,
    pub metadata: String,
}

impl From<UpdateAppArgs> for super::Reducer {
    fn from(args: UpdateAppArgs) -> Self {
        Self::UpdateApp {
            uuid: args.uuid,
            name: args.name,
            description: args.description,
            metadata: args.metadata,
        }
    }
}

impl __sdk::InModule for UpdateAppArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_app`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_app {
    /// Request that the remote module invoke the reducer `update_app` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_app:update_app_then`] to run a callback after the reducer completes.
    fn update_app(
        &self,
        uuid: String,
        name: String,
        description: String,
        metadata: String,
    ) -> __sdk::Result<()> {
        self.update_app_then(uuid, name, description, metadata, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_app` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_app_then(
        &self,
        uuid: String,
        name: String,
        description: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_app for super::RemoteReducers {
    fn update_app_then(
        &self,
        uuid: String,
        name: String,
        description: String,
        metadata: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateAppArgs {
                uuid,
                name,
                description,
                metadata,
            },
            callback,
        )
    }
}
