// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateWebhookTriggeredArgs {
    pub uuid: String,
}

impl From<UpdateWebhookTriggeredArgs> for super::Reducer {
    fn from(args: UpdateWebhookTriggeredArgs) -> Self {
        Self::UpdateWebhookTriggered { uuid: args.uuid }
    }
}

impl __sdk::InModule for UpdateWebhookTriggeredArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_webhook_triggered`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_webhook_triggered {
    /// Request that the remote module invoke the reducer `update_webhook_triggered` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_webhook_triggered:update_webhook_triggered_then`] to run a callback after the reducer completes.
    fn update_webhook_triggered(&self, uuid: String) -> __sdk::Result<()> {
        self.update_webhook_triggered_then(uuid, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_webhook_triggered` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_webhook_triggered_then(
        &self,
        uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_webhook_triggered for super::RemoteReducers {
    fn update_webhook_triggered_then(
        &self,
        uuid: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateWebhookTriggeredArgs { uuid }, callback)
    }
}
