// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct User {
    pub id: u64,
    pub uuid: String,
    pub email: String,
    pub org_id: String,
    pub role_id: String,
    pub auth_service_id: String,
    pub full_name: String,
    pub profile_picture_url: String,
    pub last_login: String,
    pub is_active: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for User {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `User`.
///
/// Provides typed access to columns for query building.
pub struct UserCols {
    pub id: __sdk::__query_builder::Col<User, u64>,
    pub uuid: __sdk::__query_builder::Col<User, String>,
    pub email: __sdk::__query_builder::Col<User, String>,
    pub org_id: __sdk::__query_builder::Col<User, String>,
    pub role_id: __sdk::__query_builder::Col<User, String>,
    pub auth_service_id: __sdk::__query_builder::Col<User, String>,
    pub full_name: __sdk::__query_builder::Col<User, String>,
    pub profile_picture_url: __sdk::__query_builder::Col<User, String>,
    pub last_login: __sdk::__query_builder::Col<User, String>,
    pub is_active: __sdk::__query_builder::Col<User, bool>,
    pub created_at: __sdk::__query_builder::Col<User, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<User, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for User {
    type Cols = UserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            auth_service_id: __sdk::__query_builder::Col::new(table_name, "auth_service_id"),
            full_name: __sdk::__query_builder::Col::new(table_name, "full_name"),
            profile_picture_url: __sdk::__query_builder::Col::new(
                table_name,
                "profile_picture_url",
            ),
            last_login: __sdk::__query_builder::Col::new(table_name, "last_login"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `User`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserIxCols {
    pub email: __sdk::__query_builder::IxCol<User, String>,
    pub id: __sdk::__query_builder::IxCol<User, u64>,
    pub org_id: __sdk::__query_builder::IxCol<User, String>,
}

impl __sdk::__query_builder::HasIxCols for User {
    type IxCols = UserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserIxCols {
            email: __sdk::__query_builder::IxCol::new(table_name, "email"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for User {}
