// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_settings_type::UserSettings;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_settings`.
///
/// Obtain a handle from the [`UserSettingsTableAccess::user_settings`] method on [`super::RemoteTables`],
/// like `ctx.db.user_settings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_settings().on_insert(...)`.
pub struct UserSettingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserSettings>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_settings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserSettingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserSettingsTableHandle`], which mediates access to the table `user_settings`.
    fn user_settings(&self) -> UserSettingsTableHandle<'_>;
}

impl UserSettingsTableAccess for super::RemoteTables {
    fn user_settings(&self) -> UserSettingsTableHandle<'_> {
        UserSettingsTableHandle {
            imp: self.imp.get_table::<UserSettings>("user_settings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserSettingsInsertCallbackId(__sdk::CallbackId);
pub struct UserSettingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserSettingsTableHandle<'ctx> {
    type Row = UserSettings;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserSettings> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserSettingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserSettingsInsertCallbackId {
        UserSettingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserSettingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserSettingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserSettingsDeleteCallbackId {
        UserSettingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserSettingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserSettingsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserSettingsTableHandle<'ctx> {
    type UpdateCallbackId = UserSettingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserSettingsUpdateCallbackId {
        UserSettingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserSettingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `user_settings`,
/// which allows point queries on the field of the same name
/// via the [`UserSettingsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_settings().id().find(...)`.
pub struct UserSettingsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserSettings, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserSettingsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `user_settings`.
    pub fn id(&self) -> UserSettingsIdUnique<'ctx> {
        UserSettingsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserSettingsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<UserSettings> {
        self.imp.find(col_val)
    }
}

/// Access to the `user_id` unique index on the table `user_settings`,
/// which allows point queries on the field of the same name
/// via the [`UserSettingsUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_settings().user_id().find(...)`.
pub struct UserSettingsUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserSettings, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserSettingsTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `user_settings`.
    pub fn user_id(&self) -> UserSettingsUserIdUnique<'ctx> {
        UserSettingsUserIdUnique {
            imp: self.imp.get_unique_constraint::<String>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserSettingsUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserSettings> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserSettings>("user_settings");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("user_id", |row| &row.user_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserSettings>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserSettings>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserSettings`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_settingsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserSettings`.
    fn user_settings(&self) -> __sdk::__query_builder::Table<UserSettings>;
}

impl user_settingsQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_settings(&self) -> __sdk::__query_builder::Table<UserSettings> {
        __sdk::__query_builder::Table::new("user_settings")
    }
}
