// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::webhook_type::Webhook;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `webhook`.
///
/// Obtain a handle from the [`WebhookTableAccess::webhook`] method on [`super::RemoteTables`],
/// like `ctx.db.webhook()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.webhook().on_insert(...)`.
pub struct WebhookTableHandle<'ctx> {
    imp: __sdk::TableHandle<Webhook>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `webhook`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WebhookTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WebhookTableHandle`], which mediates access to the table `webhook`.
    fn webhook(&self) -> WebhookTableHandle<'_>;
}

impl WebhookTableAccess for super::RemoteTables {
    fn webhook(&self) -> WebhookTableHandle<'_> {
        WebhookTableHandle {
            imp: self.imp.get_table::<Webhook>("webhook"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WebhookInsertCallbackId(__sdk::CallbackId);
pub struct WebhookDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for WebhookTableHandle<'ctx> {
    type Row = Webhook;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Webhook> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WebhookInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WebhookInsertCallbackId {
        WebhookInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WebhookInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WebhookDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WebhookDeleteCallbackId {
        WebhookDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WebhookDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WebhookUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WebhookTableHandle<'ctx> {
    type UpdateCallbackId = WebhookUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WebhookUpdateCallbackId {
        WebhookUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WebhookUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `webhook`,
/// which allows point queries on the field of the same name
/// via the [`WebhookIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.webhook().id().find(...)`.
pub struct WebhookIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Webhook, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WebhookTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `webhook`.
    pub fn id(&self) -> WebhookIdUnique<'ctx> {
        WebhookIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WebhookIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Webhook> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Webhook>("webhook");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Webhook>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Webhook>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Webhook`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait webhookQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Webhook`.
    fn webhook(&self) -> __sdk::__query_builder::Table<Webhook>;
}

impl webhookQueryTableAccess for __sdk::QueryTableAccessor {
    fn webhook(&self) -> __sdk::__query_builder::Table<Webhook> {
        __sdk::__query_builder::Table::new("webhook")
    }
}
