// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Webhook {
    pub id: u64,
    pub uuid: String,
    pub name: String,
    pub org_id: String,
    pub user_id: String,
    pub url: String,
    pub event_types: String,
    pub is_active: bool,
    pub webhook_type: String,
    pub app_id: String,
    pub linked_to: String,
    pub last_triggered_at: String,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Webhook {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Webhook`.
///
/// Provides typed access to columns for query building.
pub struct WebhookCols {
    pub id: __sdk::__query_builder::Col<Webhook, u64>,
    pub uuid: __sdk::__query_builder::Col<Webhook, String>,
    pub name: __sdk::__query_builder::Col<Webhook, String>,
    pub org_id: __sdk::__query_builder::Col<Webhook, String>,
    pub user_id: __sdk::__query_builder::Col<Webhook, String>,
    pub url: __sdk::__query_builder::Col<Webhook, String>,
    pub event_types: __sdk::__query_builder::Col<Webhook, String>,
    pub is_active: __sdk::__query_builder::Col<Webhook, bool>,
    pub webhook_type: __sdk::__query_builder::Col<Webhook, String>,
    pub app_id: __sdk::__query_builder::Col<Webhook, String>,
    pub linked_to: __sdk::__query_builder::Col<Webhook, String>,
    pub last_triggered_at: __sdk::__query_builder::Col<Webhook, String>,
    pub created_at: __sdk::__query_builder::Col<Webhook, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Webhook, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Webhook {
    type Cols = WebhookCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WebhookCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            uuid: __sdk::__query_builder::Col::new(table_name, "uuid"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            org_id: __sdk::__query_builder::Col::new(table_name, "org_id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            url: __sdk::__query_builder::Col::new(table_name, "url"),
            event_types: __sdk::__query_builder::Col::new(table_name, "event_types"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            webhook_type: __sdk::__query_builder::Col::new(table_name, "webhook_type"),
            app_id: __sdk::__query_builder::Col::new(table_name, "app_id"),
            linked_to: __sdk::__query_builder::Col::new(table_name, "linked_to"),
            last_triggered_at: __sdk::__query_builder::Col::new(table_name, "last_triggered_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Webhook`.
///
/// Provides typed access to indexed columns for query building.
pub struct WebhookIxCols {
    pub id: __sdk::__query_builder::IxCol<Webhook, u64>,
    pub org_id: __sdk::__query_builder::IxCol<Webhook, String>,
}

impl __sdk::__query_builder::HasIxCols for Webhook {
    type IxCols = WebhookIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WebhookIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            org_id: __sdk::__query_builder::IxCol::new(table_name, "org_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Webhook {}
