SHELL := /bin/bash

.DEFAULT_GOAL := help

.PHONY: help
help:
	@printf "The advanced operator-based Kubernetes path has not been implemented yet.\n"
	@printf "Use the primary Helm path from the repo root instead:\n\n"
	@printf "  make kind-create\n"
	@printf "  make helm-deps\n"
	@printf "  make helm-install-kind\n"
