import { type Bindings, pino } from "pino";
import { trace, isSpanContextValid } from "@opentelemetry/api";

export enum LogTypes {
	LOGS = "logs",
	ERROR = "error",
	CUSTOMOBJ = "customObj",
}

// Singleton Pino instance with trace context mixin for OTEL log-trace correlation
const logger = pino({
	mixin() {
		const span = trace.getActiveSpan();
		if (span) {
			const ctx = span.spanContext();
			if (isSpanContextValid(ctx)) {
				return {
					trace_id: ctx.traceId,
					span_id: ctx.spanId,
					trace_flags: `0${ctx.traceFlags.toString(16)}`,
				};
			}
		}
		return {};
	},
});

/**
 * Function to log the messages
 * @param msg  Message to be logged
 * @param logType Type of log
 * @param generated_by Generated by
 * @returns Log
 */
const infoLogs = (msg: string | Bindings, logType: LogTypes, generated_by: string) => {
	if (
		generated_by &&
		[LogTypes.LOGS, LogTypes.ERROR].includes(logType) &&
		typeof msg === "string"
	) {
		msg = `[${generated_by}] ` + msg;
	}
	if (logType === LogTypes.LOGS && typeof msg === "string") return logger.info(msg);
	if (logType === LogTypes.ERROR && typeof msg === "string") return logger.error(msg);
	return logger.child(msg as Bindings);
};

export default infoLogs;
