// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/envsync-cloud/envsync-management-go-sdk/sdk/internal"
)

type SamlSsoRequest struct {
	// SAML provider ID to initiate SSO with
	ProviderId string `json:"provider_id" url:"-"`
}

type SamlSsoResponse struct {
	// URL to redirect the user to for IdP authentication
	RedirectUrl string `json:"redirect_url" url:"redirect_url"`
	// AuthnRequest ID for tracking
	RequestId string `json:"request_id" url:"request_id"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SamlSsoResponse) GetRedirectUrl() string {
	if s == nil {
		return ""
	}
	return s.RedirectUrl
}

func (s *SamlSsoResponse) GetRequestId() string {
	if s == nil {
		return ""
	}
	return s.RequestId
}

func (s *SamlSsoResponse) GetExtraProperties() map[string]interface{} {
	return s.extraProperties
}

func (s *SamlSsoResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler SamlSsoResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SamlSsoResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SamlSsoResponse) String() string {
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}
