apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "envsync.fullname" . }}-zitadel-data
  labels:
    {{- include "envsync.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zitadel.persistence.size }}
  {{- with .Values.global.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
