apiVersion: v1
kind: Service
metadata:
  name: {{ include "envsync.fullname" . }}-zitadel
  labels:
    {{- include "envsync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "envsync.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: zitadel
  ports:
    - name: http
      port: {{ .Values.zitadel.service.port }}
      targetPort: http
